// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: circuits_v2/circuit_root_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CircuitsV2.Protobuf {

  /// <summary>Holder for reflection information generated from circuits_v2/circuit_root_data.proto</summary>
  public static partial class CircuitRootDataReflection {

    #region Descriptor
    /// <summary>File descriptor for circuits_v2/circuit_root_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CircuitRootDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNjaXJjdWl0c192Mi9jaXJjdWl0X3Jvb3RfZGF0YS5wcm90bxILY2lyY3Vp",
            "dHNfdjIaLmNpcmN1aXRzX3YyL2NpcmN1aXRfZ2xvYmFsX2VudGl0aWVzX2Rh",
            "dGEucHJvdG8aJGNpcmN1aXRzX3YyL2NpcmN1aXRfZ3JhcGhfZGF0YS5wcm90",
            "bxovY2lyY3VpdHNfdjIvY2lyY3VpdF9zZXJpYWxpemF0aW9uX3ZlcnNpb24u",
            "cHJvdG8aKmNpcmN1aXRzX3YyL3JlcGxpY2F0b3JfcmVnaXN0cnlfZGF0YS5w",
            "cm90bxo1Y2lyY3VpdHNfdjIvZGF0YV90YWJsZS9kYXRhX3RhYmxlX3JlZ2lz",
            "dHJ5X2RhdGEucHJvdG8aSmNpcmN1aXRzX3YyL3N0dWRpb19mdW5jdGlvbnMv",
            "c3R1ZGlvX2Z1bmN0aW9uX3NpZ25hdHVyZV9yZWdpc3RyeV9kYXRhLnByb3Rv",
            "GiRjaXJjdWl0c192Mi9zbmFwc2hvdF9vbmx5X2RhdGEucHJvdG8i+QMKD0Np",
            "cmN1aXRSb290RGF0YRI5Cgd2ZXJzaW9uGAEgASgOMiguY2lyY3VpdHNfdjIu",
            "Q2lyY3VpdFNlcmlhbGl6YXRpb25WZXJzaW9uEisKBHJvb3QYAiABKAsyHS5j",
            "aXJjdWl0c192Mi5DaXJjdWl0R3JhcGhEYXRhEj8KE2RhdGFfdGFibGVfcmVn",
            "aXN0cnkYAyABKAsyIi5jaXJjdWl0c192Mi5EYXRhVGFibGVSZWdpc3RyeURh",
            "dGESYQonc3R1ZGlvX2Z1bmN0aW9uX3NpZ25hdHVyZV9yZWdpc3RyeV9kYXRh",
            "GAUgASgLMjAuY2lyY3VpdHNfdjIuU3R1ZGlvRnVuY3Rpb25TaWduYXR1cmVS",
            "ZWdpc3RyeURhdGESOAoIZW50aXRpZXMYBiABKAsyJi5jaXJjdWl0c192Mi5D",
            "aXJjdWl0R2xvYmFsRW50aXRpZXNEYXRhEkUKGHJlcGxpY2F0b3JfcmVnaXN0",
            "cnlfZGF0YRgHIAEoCzIjLmNpcmN1aXRzX3YyLlJlcGxpY2F0b3JSZWdpc3Ry",
            "eURhdGESOQoSc25hcHNob3Rfb25seV9kYXRhGAggASgLMh0uY2lyY3VpdHNf",
            "djIuU25hcHNob3RPbmx5RGF0YRIeChZERVBSRUNBVEVEX21heF9wbGF5ZXJz",
            "GAQgASgFQhaqAhNDaXJjdWl0c1YyLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CircuitsV2.Protobuf.CircuitGlobalEntitiesDataReflection.Descriptor, global::CircuitsV2.Protobuf.CircuitGraphDataReflection.Descriptor, global::CircuitsV2.Protobuf.CircuitSerializationVersionReflection.Descriptor, global::CircuitsV2.Protobuf.ReplicatorRegistryDataReflection.Descriptor, global::CircuitsV2.Protobuf.DataTableRegistryDataReflection.Descriptor, global::CircuitsV2.Protobuf.StudioFunctionSignatureRegistryDataReflection.Descriptor, global::CircuitsV2.Protobuf.SnapshotOnlyDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CircuitsV2.Protobuf.CircuitRootData), global::CircuitsV2.Protobuf.CircuitRootData.Parser, new[]{ "Version", "Root", "DataTableRegistry", "StudioFunctionSignatureRegistryData", "Entities", "ReplicatorRegistryData", "SnapshotOnlyData", "DEPRECATEDMaxPlayers" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CircuitRootData : pb::IMessage<CircuitRootData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CircuitRootData> _parser = new pb::MessageParser<CircuitRootData>(() => new CircuitRootData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CircuitRootData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CircuitsV2.Protobuf.CircuitRootDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CircuitRootData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CircuitRootData(CircuitRootData other) : this() {
      version_ = other.version_;
      root_ = other.root_ != null ? other.root_.Clone() : null;
      dataTableRegistry_ = other.dataTableRegistry_ != null ? other.dataTableRegistry_.Clone() : null;
      studioFunctionSignatureRegistryData_ = other.studioFunctionSignatureRegistryData_ != null ? other.studioFunctionSignatureRegistryData_.Clone() : null;
      entities_ = other.entities_ != null ? other.entities_.Clone() : null;
      replicatorRegistryData_ = other.replicatorRegistryData_ != null ? other.replicatorRegistryData_.Clone() : null;
      snapshotOnlyData_ = other.snapshotOnlyData_ != null ? other.snapshotOnlyData_.Clone() : null;
      dEPRECATEDMaxPlayers_ = other.dEPRECATEDMaxPlayers_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CircuitRootData Clone() {
      return new CircuitRootData(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private global::CircuitsV2.Protobuf.CircuitSerializationVersion version_ = global::CircuitsV2.Protobuf.CircuitSerializationVersion.V0New;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CircuitsV2.Protobuf.CircuitSerializationVersion Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "root" field.</summary>
    public const int RootFieldNumber = 2;
    private global::CircuitsV2.Protobuf.CircuitGraphData root_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CircuitsV2.Protobuf.CircuitGraphData Root {
      get { return root_; }
      set {
        root_ = value;
      }
    }

    /// <summary>Field number for the "data_table_registry" field.</summary>
    public const int DataTableRegistryFieldNumber = 3;
    private global::CircuitsV2.Protobuf.DataTableRegistryData dataTableRegistry_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CircuitsV2.Protobuf.DataTableRegistryData DataTableRegistry {
      get { return dataTableRegistry_; }
      set {
        dataTableRegistry_ = value;
      }
    }

    /// <summary>Field number for the "studio_function_signature_registry_data" field.</summary>
    public const int StudioFunctionSignatureRegistryDataFieldNumber = 5;
    private global::CircuitsV2.Protobuf.StudioFunctionSignatureRegistryData studioFunctionSignatureRegistryData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CircuitsV2.Protobuf.StudioFunctionSignatureRegistryData StudioFunctionSignatureRegistryData {
      get { return studioFunctionSignatureRegistryData_; }
      set {
        studioFunctionSignatureRegistryData_ = value;
      }
    }

    /// <summary>Field number for the "entities" field.</summary>
    public const int EntitiesFieldNumber = 6;
    private global::CircuitsV2.Protobuf.CircuitGlobalEntitiesData entities_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CircuitsV2.Protobuf.CircuitGlobalEntitiesData Entities {
      get { return entities_; }
      set {
        entities_ = value;
      }
    }

    /// <summary>Field number for the "replicator_registry_data" field.</summary>
    public const int ReplicatorRegistryDataFieldNumber = 7;
    private global::CircuitsV2.Protobuf.ReplicatorRegistryData replicatorRegistryData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CircuitsV2.Protobuf.ReplicatorRegistryData ReplicatorRegistryData {
      get { return replicatorRegistryData_; }
      set {
        replicatorRegistryData_ = value;
      }
    }

    /// <summary>Field number for the "snapshot_only_data" field.</summary>
    public const int SnapshotOnlyDataFieldNumber = 8;
    private global::CircuitsV2.Protobuf.SnapshotOnlyData snapshotOnlyData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CircuitsV2.Protobuf.SnapshotOnlyData SnapshotOnlyData {
      get { return snapshotOnlyData_; }
      set {
        snapshotOnlyData_ = value;
      }
    }

    /// <summary>Field number for the "DEPRECATED_max_players" field.</summary>
    public const int DEPRECATEDMaxPlayersFieldNumber = 4;
    private int dEPRECATEDMaxPlayers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DEPRECATEDMaxPlayers {
      get { return dEPRECATEDMaxPlayers_; }
      set {
        dEPRECATEDMaxPlayers_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CircuitRootData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CircuitRootData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if (!object.Equals(Root, other.Root)) return false;
      if (!object.Equals(DataTableRegistry, other.DataTableRegistry)) return false;
      if (!object.Equals(StudioFunctionSignatureRegistryData, other.StudioFunctionSignatureRegistryData)) return false;
      if (!object.Equals(Entities, other.Entities)) return false;
      if (!object.Equals(ReplicatorRegistryData, other.ReplicatorRegistryData)) return false;
      if (!object.Equals(SnapshotOnlyData, other.SnapshotOnlyData)) return false;
      if (DEPRECATEDMaxPlayers != other.DEPRECATEDMaxPlayers) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Version != global::CircuitsV2.Protobuf.CircuitSerializationVersion.V0New) hash ^= Version.GetHashCode();
      if (root_ != null) hash ^= Root.GetHashCode();
      if (dataTableRegistry_ != null) hash ^= DataTableRegistry.GetHashCode();
      if (studioFunctionSignatureRegistryData_ != null) hash ^= StudioFunctionSignatureRegistryData.GetHashCode();
      if (entities_ != null) hash ^= Entities.GetHashCode();
      if (replicatorRegistryData_ != null) hash ^= ReplicatorRegistryData.GetHashCode();
      if (snapshotOnlyData_ != null) hash ^= SnapshotOnlyData.GetHashCode();
      if (DEPRECATEDMaxPlayers != 0) hash ^= DEPRECATEDMaxPlayers.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Version != global::CircuitsV2.Protobuf.CircuitSerializationVersion.V0New) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Version);
      }
      if (root_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Root);
      }
      if (dataTableRegistry_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DataTableRegistry);
      }
      if (DEPRECATEDMaxPlayers != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(DEPRECATEDMaxPlayers);
      }
      if (studioFunctionSignatureRegistryData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(StudioFunctionSignatureRegistryData);
      }
      if (entities_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Entities);
      }
      if (replicatorRegistryData_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ReplicatorRegistryData);
      }
      if (snapshotOnlyData_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(SnapshotOnlyData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Version != global::CircuitsV2.Protobuf.CircuitSerializationVersion.V0New) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Version);
      }
      if (root_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Root);
      }
      if (dataTableRegistry_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DataTableRegistry);
      }
      if (DEPRECATEDMaxPlayers != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(DEPRECATEDMaxPlayers);
      }
      if (studioFunctionSignatureRegistryData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(StudioFunctionSignatureRegistryData);
      }
      if (entities_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Entities);
      }
      if (replicatorRegistryData_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ReplicatorRegistryData);
      }
      if (snapshotOnlyData_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(SnapshotOnlyData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Version != global::CircuitsV2.Protobuf.CircuitSerializationVersion.V0New) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Version);
      }
      if (root_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Root);
      }
      if (dataTableRegistry_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataTableRegistry);
      }
      if (studioFunctionSignatureRegistryData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StudioFunctionSignatureRegistryData);
      }
      if (entities_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Entities);
      }
      if (replicatorRegistryData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReplicatorRegistryData);
      }
      if (snapshotOnlyData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SnapshotOnlyData);
      }
      if (DEPRECATEDMaxPlayers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DEPRECATEDMaxPlayers);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CircuitRootData other) {
      if (other == null) {
        return;
      }
      if (other.Version != global::CircuitsV2.Protobuf.CircuitSerializationVersion.V0New) {
        Version = other.Version;
      }
      if (other.root_ != null) {
        if (root_ == null) {
          Root = new global::CircuitsV2.Protobuf.CircuitGraphData();
        }
        Root.MergeFrom(other.Root);
      }
      if (other.dataTableRegistry_ != null) {
        if (dataTableRegistry_ == null) {
          DataTableRegistry = new global::CircuitsV2.Protobuf.DataTableRegistryData();
        }
        DataTableRegistry.MergeFrom(other.DataTableRegistry);
      }
      if (other.studioFunctionSignatureRegistryData_ != null) {
        if (studioFunctionSignatureRegistryData_ == null) {
          StudioFunctionSignatureRegistryData = new global::CircuitsV2.Protobuf.StudioFunctionSignatureRegistryData();
        }
        StudioFunctionSignatureRegistryData.MergeFrom(other.StudioFunctionSignatureRegistryData);
      }
      if (other.entities_ != null) {
        if (entities_ == null) {
          Entities = new global::CircuitsV2.Protobuf.CircuitGlobalEntitiesData();
        }
        Entities.MergeFrom(other.Entities);
      }
      if (other.replicatorRegistryData_ != null) {
        if (replicatorRegistryData_ == null) {
          ReplicatorRegistryData = new global::CircuitsV2.Protobuf.ReplicatorRegistryData();
        }
        ReplicatorRegistryData.MergeFrom(other.ReplicatorRegistryData);
      }
      if (other.snapshotOnlyData_ != null) {
        if (snapshotOnlyData_ == null) {
          SnapshotOnlyData = new global::CircuitsV2.Protobuf.SnapshotOnlyData();
        }
        SnapshotOnlyData.MergeFrom(other.SnapshotOnlyData);
      }
      if (other.DEPRECATEDMaxPlayers != 0) {
        DEPRECATEDMaxPlayers = other.DEPRECATEDMaxPlayers;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Version = (global::CircuitsV2.Protobuf.CircuitSerializationVersion) input.ReadEnum();
            break;
          }
          case 18: {
            if (root_ == null) {
              Root = new global::CircuitsV2.Protobuf.CircuitGraphData();
            }
            input.ReadMessage(Root);
            break;
          }
          case 26: {
            if (dataTableRegistry_ == null) {
              DataTableRegistry = new global::CircuitsV2.Protobuf.DataTableRegistryData();
            }
            input.ReadMessage(DataTableRegistry);
            break;
          }
          case 32: {
            DEPRECATEDMaxPlayers = input.ReadInt32();
            break;
          }
          case 42: {
            if (studioFunctionSignatureRegistryData_ == null) {
              StudioFunctionSignatureRegistryData = new global::CircuitsV2.Protobuf.StudioFunctionSignatureRegistryData();
            }
            input.ReadMessage(StudioFunctionSignatureRegistryData);
            break;
          }
          case 50: {
            if (entities_ == null) {
              Entities = new global::CircuitsV2.Protobuf.CircuitGlobalEntitiesData();
            }
            input.ReadMessage(Entities);
            break;
          }
          case 58: {
            if (replicatorRegistryData_ == null) {
              ReplicatorRegistryData = new global::CircuitsV2.Protobuf.ReplicatorRegistryData();
            }
            input.ReadMessage(ReplicatorRegistryData);
            break;
          }
          case 66: {
            if (snapshotOnlyData_ == null) {
              SnapshotOnlyData = new global::CircuitsV2.Protobuf.SnapshotOnlyData();
            }
            input.ReadMessage(SnapshotOnlyData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Version = (global::CircuitsV2.Protobuf.CircuitSerializationVersion) input.ReadEnum();
            break;
          }
          case 18: {
            if (root_ == null) {
              Root = new global::CircuitsV2.Protobuf.CircuitGraphData();
            }
            input.ReadMessage(Root);
            break;
          }
          case 26: {
            if (dataTableRegistry_ == null) {
              DataTableRegistry = new global::CircuitsV2.Protobuf.DataTableRegistryData();
            }
            input.ReadMessage(DataTableRegistry);
            break;
          }
          case 32: {
            DEPRECATEDMaxPlayers = input.ReadInt32();
            break;
          }
          case 42: {
            if (studioFunctionSignatureRegistryData_ == null) {
              StudioFunctionSignatureRegistryData = new global::CircuitsV2.Protobuf.StudioFunctionSignatureRegistryData();
            }
            input.ReadMessage(StudioFunctionSignatureRegistryData);
            break;
          }
          case 50: {
            if (entities_ == null) {
              Entities = new global::CircuitsV2.Protobuf.CircuitGlobalEntitiesData();
            }
            input.ReadMessage(Entities);
            break;
          }
          case 58: {
            if (replicatorRegistryData_ == null) {
              ReplicatorRegistryData = new global::CircuitsV2.Protobuf.ReplicatorRegistryData();
            }
            input.ReadMessage(ReplicatorRegistryData);
            break;
          }
          case 66: {
            if (snapshotOnlyData_ == null) {
              SnapshotOnlyData = new global::CircuitsV2.Protobuf.SnapshotOnlyData();
            }
            input.ReadMessage(SnapshotOnlyData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
