// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: circuits_v2/cloud_data_ledger_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CircuitsV2.Protobuf {

  /// <summary>Holder for reflection information generated from circuits_v2/cloud_data_ledger_data.proto</summary>
  public static partial class CloudDataLedgerDataReflection {

    #region Descriptor
    /// <summary>File descriptor for circuits_v2/cloud_data_ledger_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CloudDataLedgerDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihjaXJjdWl0c192Mi9jbG91ZF9kYXRhX2xlZGdlcl9kYXRhLnByb3RvEgtj",
            "aXJjdWl0c192MhpBY2lyY3VpdHNfdjIvZGVwcmVjYXRlZC9ERVBSRUNBVEVE",
            "X2Nsb3VkX2RhdGFfbGVkZ2VyX3ZlcnNpb24ucHJvdG8aLmNpcmN1aXRzX3Yy",
            "L2Nsb3VkX2RhdGFfbGVkZ2VyX2VudHJ5X2RhdGEucHJvdG8ilAkKE0Nsb3Vk",
            "RGF0YUxlZGdlckRhdGESNAoFYm9vbHMYAiADKAsyJS5jaXJjdWl0c192Mi5D",
            "bG91ZERhdGFMZWRnZXJFbnRyeURhdGESNQoGZmxvYXRzGAMgAygLMiUuY2ly",
            "Y3VpdHNfdjIuQ2xvdWREYXRhTGVkZ2VyRW50cnlEYXRhEjMKBGludHMYBCAD",
            "KAsyJS5jaXJjdWl0c192Mi5DbG91ZERhdGFMZWRnZXJFbnRyeURhdGESOgoL",
            "cXVhdGVybmlvbnMYBSADKAsyJS5jaXJjdWl0c192Mi5DbG91ZERhdGFMZWRn",
            "ZXJFbnRyeURhdGESNgoHc3RyaW5ncxgGIAMoCzIlLmNpcmN1aXRzX3YyLkNs",
            "b3VkRGF0YUxlZGdlckVudHJ5RGF0YRI3Cgh2ZWN0b3IzcxgHIAMoCzIlLmNp",
            "cmN1aXRzX3YyLkNsb3VkRGF0YUxlZGdlckVudHJ5RGF0YRI1CgZjb2xvcnMY",
            "CCADKAsyJS5jaXJjdWl0c192Mi5DbG91ZERhdGFMZWRnZXJFbnRyeURhdGES",
            "PAoNcmVjX25ldF9pbWFnZRgQIAMoCzIlLmNpcmN1aXRzX3YyLkNsb3VkRGF0",
            "YUxlZGdlckVudHJ5RGF0YRI9Cg5yZWNfbmV0X21lc2hlcxgSIAMoCzIlLmNp",
            "cmN1aXRzX3YyLkNsb3VkRGF0YUxlZGdlckVudHJ5RGF0YRI5CgpsaXN0X2Jv",
            "b2xzGAkgAygLMiUuY2lyY3VpdHNfdjIuQ2xvdWREYXRhTGVkZ2VyRW50cnlE",
            "YXRhEjoKC2xpc3RfZmxvYXRzGAogAygLMiUuY2lyY3VpdHNfdjIuQ2xvdWRE",
            "YXRhTGVkZ2VyRW50cnlEYXRhEjgKCWxpc3RfaW50cxgLIAMoCzIlLmNpcmN1",
            "aXRzX3YyLkNsb3VkRGF0YUxlZGdlckVudHJ5RGF0YRI/ChBsaXN0X3F1YXRl",
            "cm5pb25zGAwgAygLMiUuY2lyY3VpdHNfdjIuQ2xvdWREYXRhTGVkZ2VyRW50",
            "cnlEYXRhEjsKDGxpc3Rfc3RyaW5ncxgNIAMoCzIlLmNpcmN1aXRzX3YyLkNs",
            "b3VkRGF0YUxlZGdlckVudHJ5RGF0YRI8Cg1saXN0X3ZlY3RvcjNzGA4gAygL",
            "MiUuY2lyY3VpdHNfdjIuQ2xvdWREYXRhTGVkZ2VyRW50cnlEYXRhEjoKC2xp",
            "c3RfY29sb3JzGA8gAygLMiUuY2lyY3VpdHNfdjIuQ2xvdWREYXRhTGVkZ2Vy",
            "RW50cnlEYXRhEkEKEmxpc3RfcmVjX25ldF9pbWFnZRgRIAMoCzIlLmNpcmN1",
            "aXRzX3YyLkNsb3VkRGF0YUxlZGdlckVudHJ5RGF0YRJCChNsaXN0X3JlY19u",
            "ZXRfbWVzaGVzGBMgAygLMiUuY2lyY3VpdHNfdjIuQ2xvdWREYXRhTGVkZ2Vy",
            "RW50cnlEYXRhEkoKEkRFUFJFQ0FURURfVmVyc2lvbhgBIAEoDjIuLmNpcmN1",
            "aXRzX3YyLkRFUFJFQ0FURURfQ2xvdWREYXRhTGVkZ2VyVmVyc2lvbkIWqgIT",
            "Q2lyY3VpdHNWMi5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CircuitsV2.Protobuf.DEPRECATEDCloudDataLedgerVersionReflection.Descriptor, global::CircuitsV2.Protobuf.CloudDataLedgerEntryDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CircuitsV2.Protobuf.CloudDataLedgerData), global::CircuitsV2.Protobuf.CloudDataLedgerData.Parser, new[]{ "Bools", "Floats", "Ints", "Quaternions", "Strings", "Vector3S", "Colors", "RecNetImage", "RecNetMeshes", "ListBools", "ListFloats", "ListInts", "ListQuaternions", "ListStrings", "ListVector3S", "ListColors", "ListRecNetImage", "ListRecNetMeshes", "DEPRECATEDVersion" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CloudDataLedgerData : pb::IMessage<CloudDataLedgerData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CloudDataLedgerData> _parser = new pb::MessageParser<CloudDataLedgerData>(() => new CloudDataLedgerData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CloudDataLedgerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CircuitsV2.Protobuf.CloudDataLedgerDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudDataLedgerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudDataLedgerData(CloudDataLedgerData other) : this() {
      bools_ = other.bools_.Clone();
      floats_ = other.floats_.Clone();
      ints_ = other.ints_.Clone();
      quaternions_ = other.quaternions_.Clone();
      strings_ = other.strings_.Clone();
      vector3S_ = other.vector3S_.Clone();
      colors_ = other.colors_.Clone();
      recNetImage_ = other.recNetImage_.Clone();
      recNetMeshes_ = other.recNetMeshes_.Clone();
      listBools_ = other.listBools_.Clone();
      listFloats_ = other.listFloats_.Clone();
      listInts_ = other.listInts_.Clone();
      listQuaternions_ = other.listQuaternions_.Clone();
      listStrings_ = other.listStrings_.Clone();
      listVector3S_ = other.listVector3S_.Clone();
      listColors_ = other.listColors_.Clone();
      listRecNetImage_ = other.listRecNetImage_.Clone();
      listRecNetMeshes_ = other.listRecNetMeshes_.Clone();
      dEPRECATEDVersion_ = other.dEPRECATEDVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudDataLedgerData Clone() {
      return new CloudDataLedgerData(this);
    }

    /// <summary>Field number for the "bools" field.</summary>
    public const int BoolsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_bools_codec
        = pb::FieldCodec.ForMessage(18, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> bools_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> Bools {
      get { return bools_; }
    }

    /// <summary>Field number for the "floats" field.</summary>
    public const int FloatsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_floats_codec
        = pb::FieldCodec.ForMessage(26, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> floats_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> Floats {
      get { return floats_; }
    }

    /// <summary>Field number for the "ints" field.</summary>
    public const int IntsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_ints_codec
        = pb::FieldCodec.ForMessage(34, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ints_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> Ints {
      get { return ints_; }
    }

    /// <summary>Field number for the "quaternions" field.</summary>
    public const int QuaternionsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_quaternions_codec
        = pb::FieldCodec.ForMessage(42, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> quaternions_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> Quaternions {
      get { return quaternions_; }
    }

    /// <summary>Field number for the "strings" field.</summary>
    public const int StringsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_strings_codec
        = pb::FieldCodec.ForMessage(50, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> strings_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> Strings {
      get { return strings_; }
    }

    /// <summary>Field number for the "vector3s" field.</summary>
    public const int Vector3SFieldNumber = 7;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_vector3S_codec
        = pb::FieldCodec.ForMessage(58, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> vector3S_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> Vector3S {
      get { return vector3S_; }
    }

    /// <summary>Field number for the "colors" field.</summary>
    public const int ColorsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_colors_codec
        = pb::FieldCodec.ForMessage(66, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> colors_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> Colors {
      get { return colors_; }
    }

    /// <summary>Field number for the "rec_net_image" field.</summary>
    public const int RecNetImageFieldNumber = 16;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_recNetImage_codec
        = pb::FieldCodec.ForMessage(130, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> recNetImage_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> RecNetImage {
      get { return recNetImage_; }
    }

    /// <summary>Field number for the "rec_net_meshes" field.</summary>
    public const int RecNetMeshesFieldNumber = 18;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_recNetMeshes_codec
        = pb::FieldCodec.ForMessage(146, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> recNetMeshes_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> RecNetMeshes {
      get { return recNetMeshes_; }
    }

    /// <summary>Field number for the "list_bools" field.</summary>
    public const int ListBoolsFieldNumber = 9;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listBools_codec
        = pb::FieldCodec.ForMessage(74, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listBools_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListBools {
      get { return listBools_; }
    }

    /// <summary>Field number for the "list_floats" field.</summary>
    public const int ListFloatsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listFloats_codec
        = pb::FieldCodec.ForMessage(82, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listFloats_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListFloats {
      get { return listFloats_; }
    }

    /// <summary>Field number for the "list_ints" field.</summary>
    public const int ListIntsFieldNumber = 11;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listInts_codec
        = pb::FieldCodec.ForMessage(90, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listInts_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListInts {
      get { return listInts_; }
    }

    /// <summary>Field number for the "list_quaternions" field.</summary>
    public const int ListQuaternionsFieldNumber = 12;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listQuaternions_codec
        = pb::FieldCodec.ForMessage(98, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listQuaternions_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListQuaternions {
      get { return listQuaternions_; }
    }

    /// <summary>Field number for the "list_strings" field.</summary>
    public const int ListStringsFieldNumber = 13;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listStrings_codec
        = pb::FieldCodec.ForMessage(106, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listStrings_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListStrings {
      get { return listStrings_; }
    }

    /// <summary>Field number for the "list_vector3s" field.</summary>
    public const int ListVector3SFieldNumber = 14;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listVector3S_codec
        = pb::FieldCodec.ForMessage(114, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listVector3S_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListVector3S {
      get { return listVector3S_; }
    }

    /// <summary>Field number for the "list_colors" field.</summary>
    public const int ListColorsFieldNumber = 15;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listColors_codec
        = pb::FieldCodec.ForMessage(122, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listColors_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListColors {
      get { return listColors_; }
    }

    /// <summary>Field number for the "list_rec_net_image" field.</summary>
    public const int ListRecNetImageFieldNumber = 17;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listRecNetImage_codec
        = pb::FieldCodec.ForMessage(138, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listRecNetImage_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListRecNetImage {
      get { return listRecNetImage_; }
    }

    /// <summary>Field number for the "list_rec_net_meshes" field.</summary>
    public const int ListRecNetMeshesFieldNumber = 19;
    private static readonly pb::FieldCodec<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> _repeated_listRecNetMeshes_codec
        = pb::FieldCodec.ForMessage(154, global::CircuitsV2.Protobuf.CloudDataLedgerEntryData.Parser);
    private readonly pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> listRecNetMeshes_ = new pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CircuitsV2.Protobuf.CloudDataLedgerEntryData> ListRecNetMeshes {
      get { return listRecNetMeshes_; }
    }

    /// <summary>Field number for the "DEPRECATED_Version" field.</summary>
    public const int DEPRECATEDVersionFieldNumber = 1;
    private global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion dEPRECATEDVersion_ = global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion.V0NewCloudDataLedgerVersion;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion DEPRECATEDVersion {
      get { return dEPRECATEDVersion_; }
      set {
        dEPRECATEDVersion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CloudDataLedgerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CloudDataLedgerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!bools_.Equals(other.bools_)) return false;
      if(!floats_.Equals(other.floats_)) return false;
      if(!ints_.Equals(other.ints_)) return false;
      if(!quaternions_.Equals(other.quaternions_)) return false;
      if(!strings_.Equals(other.strings_)) return false;
      if(!vector3S_.Equals(other.vector3S_)) return false;
      if(!colors_.Equals(other.colors_)) return false;
      if(!recNetImage_.Equals(other.recNetImage_)) return false;
      if(!recNetMeshes_.Equals(other.recNetMeshes_)) return false;
      if(!listBools_.Equals(other.listBools_)) return false;
      if(!listFloats_.Equals(other.listFloats_)) return false;
      if(!listInts_.Equals(other.listInts_)) return false;
      if(!listQuaternions_.Equals(other.listQuaternions_)) return false;
      if(!listStrings_.Equals(other.listStrings_)) return false;
      if(!listVector3S_.Equals(other.listVector3S_)) return false;
      if(!listColors_.Equals(other.listColors_)) return false;
      if(!listRecNetImage_.Equals(other.listRecNetImage_)) return false;
      if(!listRecNetMeshes_.Equals(other.listRecNetMeshes_)) return false;
      if (DEPRECATEDVersion != other.DEPRECATEDVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= bools_.GetHashCode();
      hash ^= floats_.GetHashCode();
      hash ^= ints_.GetHashCode();
      hash ^= quaternions_.GetHashCode();
      hash ^= strings_.GetHashCode();
      hash ^= vector3S_.GetHashCode();
      hash ^= colors_.GetHashCode();
      hash ^= recNetImage_.GetHashCode();
      hash ^= recNetMeshes_.GetHashCode();
      hash ^= listBools_.GetHashCode();
      hash ^= listFloats_.GetHashCode();
      hash ^= listInts_.GetHashCode();
      hash ^= listQuaternions_.GetHashCode();
      hash ^= listStrings_.GetHashCode();
      hash ^= listVector3S_.GetHashCode();
      hash ^= listColors_.GetHashCode();
      hash ^= listRecNetImage_.GetHashCode();
      hash ^= listRecNetMeshes_.GetHashCode();
      if (DEPRECATEDVersion != global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion.V0NewCloudDataLedgerVersion) hash ^= DEPRECATEDVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DEPRECATEDVersion != global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion.V0NewCloudDataLedgerVersion) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DEPRECATEDVersion);
      }
      bools_.WriteTo(output, _repeated_bools_codec);
      floats_.WriteTo(output, _repeated_floats_codec);
      ints_.WriteTo(output, _repeated_ints_codec);
      quaternions_.WriteTo(output, _repeated_quaternions_codec);
      strings_.WriteTo(output, _repeated_strings_codec);
      vector3S_.WriteTo(output, _repeated_vector3S_codec);
      colors_.WriteTo(output, _repeated_colors_codec);
      listBools_.WriteTo(output, _repeated_listBools_codec);
      listFloats_.WriteTo(output, _repeated_listFloats_codec);
      listInts_.WriteTo(output, _repeated_listInts_codec);
      listQuaternions_.WriteTo(output, _repeated_listQuaternions_codec);
      listStrings_.WriteTo(output, _repeated_listStrings_codec);
      listVector3S_.WriteTo(output, _repeated_listVector3S_codec);
      listColors_.WriteTo(output, _repeated_listColors_codec);
      recNetImage_.WriteTo(output, _repeated_recNetImage_codec);
      listRecNetImage_.WriteTo(output, _repeated_listRecNetImage_codec);
      recNetMeshes_.WriteTo(output, _repeated_recNetMeshes_codec);
      listRecNetMeshes_.WriteTo(output, _repeated_listRecNetMeshes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DEPRECATEDVersion != global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion.V0NewCloudDataLedgerVersion) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DEPRECATEDVersion);
      }
      bools_.WriteTo(ref output, _repeated_bools_codec);
      floats_.WriteTo(ref output, _repeated_floats_codec);
      ints_.WriteTo(ref output, _repeated_ints_codec);
      quaternions_.WriteTo(ref output, _repeated_quaternions_codec);
      strings_.WriteTo(ref output, _repeated_strings_codec);
      vector3S_.WriteTo(ref output, _repeated_vector3S_codec);
      colors_.WriteTo(ref output, _repeated_colors_codec);
      listBools_.WriteTo(ref output, _repeated_listBools_codec);
      listFloats_.WriteTo(ref output, _repeated_listFloats_codec);
      listInts_.WriteTo(ref output, _repeated_listInts_codec);
      listQuaternions_.WriteTo(ref output, _repeated_listQuaternions_codec);
      listStrings_.WriteTo(ref output, _repeated_listStrings_codec);
      listVector3S_.WriteTo(ref output, _repeated_listVector3S_codec);
      listColors_.WriteTo(ref output, _repeated_listColors_codec);
      recNetImage_.WriteTo(ref output, _repeated_recNetImage_codec);
      listRecNetImage_.WriteTo(ref output, _repeated_listRecNetImage_codec);
      recNetMeshes_.WriteTo(ref output, _repeated_recNetMeshes_codec);
      listRecNetMeshes_.WriteTo(ref output, _repeated_listRecNetMeshes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += bools_.CalculateSize(_repeated_bools_codec);
      size += floats_.CalculateSize(_repeated_floats_codec);
      size += ints_.CalculateSize(_repeated_ints_codec);
      size += quaternions_.CalculateSize(_repeated_quaternions_codec);
      size += strings_.CalculateSize(_repeated_strings_codec);
      size += vector3S_.CalculateSize(_repeated_vector3S_codec);
      size += colors_.CalculateSize(_repeated_colors_codec);
      size += recNetImage_.CalculateSize(_repeated_recNetImage_codec);
      size += recNetMeshes_.CalculateSize(_repeated_recNetMeshes_codec);
      size += listBools_.CalculateSize(_repeated_listBools_codec);
      size += listFloats_.CalculateSize(_repeated_listFloats_codec);
      size += listInts_.CalculateSize(_repeated_listInts_codec);
      size += listQuaternions_.CalculateSize(_repeated_listQuaternions_codec);
      size += listStrings_.CalculateSize(_repeated_listStrings_codec);
      size += listVector3S_.CalculateSize(_repeated_listVector3S_codec);
      size += listColors_.CalculateSize(_repeated_listColors_codec);
      size += listRecNetImage_.CalculateSize(_repeated_listRecNetImage_codec);
      size += listRecNetMeshes_.CalculateSize(_repeated_listRecNetMeshes_codec);
      if (DEPRECATEDVersion != global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion.V0NewCloudDataLedgerVersion) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DEPRECATEDVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CloudDataLedgerData other) {
      if (other == null) {
        return;
      }
      bools_.Add(other.bools_);
      floats_.Add(other.floats_);
      ints_.Add(other.ints_);
      quaternions_.Add(other.quaternions_);
      strings_.Add(other.strings_);
      vector3S_.Add(other.vector3S_);
      colors_.Add(other.colors_);
      recNetImage_.Add(other.recNetImage_);
      recNetMeshes_.Add(other.recNetMeshes_);
      listBools_.Add(other.listBools_);
      listFloats_.Add(other.listFloats_);
      listInts_.Add(other.listInts_);
      listQuaternions_.Add(other.listQuaternions_);
      listStrings_.Add(other.listStrings_);
      listVector3S_.Add(other.listVector3S_);
      listColors_.Add(other.listColors_);
      listRecNetImage_.Add(other.listRecNetImage_);
      listRecNetMeshes_.Add(other.listRecNetMeshes_);
      if (other.DEPRECATEDVersion != global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion.V0NewCloudDataLedgerVersion) {
        DEPRECATEDVersion = other.DEPRECATEDVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DEPRECATEDVersion = (global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion) input.ReadEnum();
            break;
          }
          case 18: {
            bools_.AddEntriesFrom(input, _repeated_bools_codec);
            break;
          }
          case 26: {
            floats_.AddEntriesFrom(input, _repeated_floats_codec);
            break;
          }
          case 34: {
            ints_.AddEntriesFrom(input, _repeated_ints_codec);
            break;
          }
          case 42: {
            quaternions_.AddEntriesFrom(input, _repeated_quaternions_codec);
            break;
          }
          case 50: {
            strings_.AddEntriesFrom(input, _repeated_strings_codec);
            break;
          }
          case 58: {
            vector3S_.AddEntriesFrom(input, _repeated_vector3S_codec);
            break;
          }
          case 66: {
            colors_.AddEntriesFrom(input, _repeated_colors_codec);
            break;
          }
          case 74: {
            listBools_.AddEntriesFrom(input, _repeated_listBools_codec);
            break;
          }
          case 82: {
            listFloats_.AddEntriesFrom(input, _repeated_listFloats_codec);
            break;
          }
          case 90: {
            listInts_.AddEntriesFrom(input, _repeated_listInts_codec);
            break;
          }
          case 98: {
            listQuaternions_.AddEntriesFrom(input, _repeated_listQuaternions_codec);
            break;
          }
          case 106: {
            listStrings_.AddEntriesFrom(input, _repeated_listStrings_codec);
            break;
          }
          case 114: {
            listVector3S_.AddEntriesFrom(input, _repeated_listVector3S_codec);
            break;
          }
          case 122: {
            listColors_.AddEntriesFrom(input, _repeated_listColors_codec);
            break;
          }
          case 130: {
            recNetImage_.AddEntriesFrom(input, _repeated_recNetImage_codec);
            break;
          }
          case 138: {
            listRecNetImage_.AddEntriesFrom(input, _repeated_listRecNetImage_codec);
            break;
          }
          case 146: {
            recNetMeshes_.AddEntriesFrom(input, _repeated_recNetMeshes_codec);
            break;
          }
          case 154: {
            listRecNetMeshes_.AddEntriesFrom(input, _repeated_listRecNetMeshes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DEPRECATEDVersion = (global::CircuitsV2.Protobuf.DEPRECATED_CloudDataLedgerVersion) input.ReadEnum();
            break;
          }
          case 18: {
            bools_.AddEntriesFrom(ref input, _repeated_bools_codec);
            break;
          }
          case 26: {
            floats_.AddEntriesFrom(ref input, _repeated_floats_codec);
            break;
          }
          case 34: {
            ints_.AddEntriesFrom(ref input, _repeated_ints_codec);
            break;
          }
          case 42: {
            quaternions_.AddEntriesFrom(ref input, _repeated_quaternions_codec);
            break;
          }
          case 50: {
            strings_.AddEntriesFrom(ref input, _repeated_strings_codec);
            break;
          }
          case 58: {
            vector3S_.AddEntriesFrom(ref input, _repeated_vector3S_codec);
            break;
          }
          case 66: {
            colors_.AddEntriesFrom(ref input, _repeated_colors_codec);
            break;
          }
          case 74: {
            listBools_.AddEntriesFrom(ref input, _repeated_listBools_codec);
            break;
          }
          case 82: {
            listFloats_.AddEntriesFrom(ref input, _repeated_listFloats_codec);
            break;
          }
          case 90: {
            listInts_.AddEntriesFrom(ref input, _repeated_listInts_codec);
            break;
          }
          case 98: {
            listQuaternions_.AddEntriesFrom(ref input, _repeated_listQuaternions_codec);
            break;
          }
          case 106: {
            listStrings_.AddEntriesFrom(ref input, _repeated_listStrings_codec);
            break;
          }
          case 114: {
            listVector3S_.AddEntriesFrom(ref input, _repeated_listVector3S_codec);
            break;
          }
          case 122: {
            listColors_.AddEntriesFrom(ref input, _repeated_listColors_codec);
            break;
          }
          case 130: {
            recNetImage_.AddEntriesFrom(ref input, _repeated_recNetImage_codec);
            break;
          }
          case 138: {
            listRecNetImage_.AddEntriesFrom(ref input, _repeated_listRecNetImage_codec);
            break;
          }
          case 146: {
            recNetMeshes_.AddEntriesFrom(ref input, _repeated_recNetMeshes_codec);
            break;
          }
          case 154: {
            listRecNetMeshes_.AddEntriesFrom(ref input, _repeated_listRecNetMeshes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
