// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: circuits_v2/deprecated/DEPRECATED_event_registration_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CircuitsV2.Protobuf {

  /// <summary>Holder for reflection information generated from circuits_v2/deprecated/DEPRECATED_event_registration_data.proto</summary>
  public static partial class DEPRECATEDEventRegistrationDataReflection {

    #region Descriptor
    /// <summary>File descriptor for circuits_v2/deprecated/DEPRECATED_event_registration_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DEPRECATEDEventRegistrationDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj9jaXJjdWl0c192Mi9kZXByZWNhdGVkL0RFUFJFQ0FURURfZXZlbnRfcmVn",
            "aXN0cmF0aW9uX2RhdGEucHJvdG8SC2NpcmN1aXRzX3YyGhRjb3JlL2d1aWRf",
            "ZGF0YS5wcm90byKUAgogREVQUkVDQVRFRF9FdmVudFJlZ2lzdHJhdGlvbkRh",
            "dGESMAoYcmVnaXN0ZXJlZF90b19jb250ZXh0X2lkGAUgASgLMg4uY29yZS5H",
            "dWlkRGF0YRIrChNldmVudF9kZWZpbml0aW9uX2lkGAYgASgLMg4uY29yZS5H",
            "dWlkRGF0YRIrCiNERVBSRUNBVEVEX3JlZ2lzdGVyZWRfdG9fY29udGV4dF9p",
            "ZBgBIAEoDBImCh5ERVBSRUNBVEVEX2V2ZW50X2RlZmluaXRpb25faWQYAiAB",
            "KAwSHAoUREVQUkVDQVRFRF9pc19nbG9iYWwYAyABKAgSHgoWREVQUkVDQVRF",
            "RF9pc19idWlsdF9pbhgEIAEoCEIWqgITQ2lyY3VpdHNWMi5Qcm90b2J1ZmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::RecRoom.Protobuf.Core.GuidDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CircuitsV2.Protobuf.DEPRECATED_EventRegistrationData), global::CircuitsV2.Protobuf.DEPRECATED_EventRegistrationData.Parser, new[]{ "RegisteredToContextId", "EventDefinitionId", "DEPRECATEDRegisteredToContextId", "DEPRECATEDEventDefinitionId", "DEPRECATEDIsGlobal", "DEPRECATEDIsBuiltIn" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DEPRECATED_EventRegistrationData : pb::IMessage<DEPRECATED_EventRegistrationData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DEPRECATED_EventRegistrationData> _parser = new pb::MessageParser<DEPRECATED_EventRegistrationData>(() => new DEPRECATED_EventRegistrationData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DEPRECATED_EventRegistrationData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CircuitsV2.Protobuf.DEPRECATEDEventRegistrationDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DEPRECATED_EventRegistrationData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DEPRECATED_EventRegistrationData(DEPRECATED_EventRegistrationData other) : this() {
      registeredToContextId_ = other.registeredToContextId_ != null ? other.registeredToContextId_.Clone() : null;
      eventDefinitionId_ = other.eventDefinitionId_ != null ? other.eventDefinitionId_.Clone() : null;
      dEPRECATEDRegisteredToContextId_ = other.dEPRECATEDRegisteredToContextId_;
      dEPRECATEDEventDefinitionId_ = other.dEPRECATEDEventDefinitionId_;
      dEPRECATEDIsGlobal_ = other.dEPRECATEDIsGlobal_;
      dEPRECATEDIsBuiltIn_ = other.dEPRECATEDIsBuiltIn_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DEPRECATED_EventRegistrationData Clone() {
      return new DEPRECATED_EventRegistrationData(this);
    }

    /// <summary>Field number for the "registered_to_context_id" field.</summary>
    public const int RegisteredToContextIdFieldNumber = 5;
    private global::RecRoom.Protobuf.Core.GuidData registeredToContextId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.Core.GuidData RegisteredToContextId {
      get { return registeredToContextId_; }
      set {
        registeredToContextId_ = value;
      }
    }

    /// <summary>Field number for the "event_definition_id" field.</summary>
    public const int EventDefinitionIdFieldNumber = 6;
    private global::RecRoom.Protobuf.Core.GuidData eventDefinitionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.Core.GuidData EventDefinitionId {
      get { return eventDefinitionId_; }
      set {
        eventDefinitionId_ = value;
      }
    }

    /// <summary>Field number for the "DEPRECATED_registered_to_context_id" field.</summary>
    public const int DEPRECATEDRegisteredToContextIdFieldNumber = 1;
    private pb::ByteString dEPRECATEDRegisteredToContextId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DEPRECATEDRegisteredToContextId {
      get { return dEPRECATEDRegisteredToContextId_; }
      set {
        dEPRECATEDRegisteredToContextId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DEPRECATED_event_definition_id" field.</summary>
    public const int DEPRECATEDEventDefinitionIdFieldNumber = 2;
    private pb::ByteString dEPRECATEDEventDefinitionId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DEPRECATEDEventDefinitionId {
      get { return dEPRECATEDEventDefinitionId_; }
      set {
        dEPRECATEDEventDefinitionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DEPRECATED_is_global" field.</summary>
    public const int DEPRECATEDIsGlobalFieldNumber = 3;
    private bool dEPRECATEDIsGlobal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DEPRECATEDIsGlobal {
      get { return dEPRECATEDIsGlobal_; }
      set {
        dEPRECATEDIsGlobal_ = value;
      }
    }

    /// <summary>Field number for the "DEPRECATED_is_built_in" field.</summary>
    public const int DEPRECATEDIsBuiltInFieldNumber = 4;
    private bool dEPRECATEDIsBuiltIn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DEPRECATEDIsBuiltIn {
      get { return dEPRECATEDIsBuiltIn_; }
      set {
        dEPRECATEDIsBuiltIn_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DEPRECATED_EventRegistrationData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DEPRECATED_EventRegistrationData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RegisteredToContextId, other.RegisteredToContextId)) return false;
      if (!object.Equals(EventDefinitionId, other.EventDefinitionId)) return false;
      if (DEPRECATEDRegisteredToContextId != other.DEPRECATEDRegisteredToContextId) return false;
      if (DEPRECATEDEventDefinitionId != other.DEPRECATEDEventDefinitionId) return false;
      if (DEPRECATEDIsGlobal != other.DEPRECATEDIsGlobal) return false;
      if (DEPRECATEDIsBuiltIn != other.DEPRECATEDIsBuiltIn) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (registeredToContextId_ != null) hash ^= RegisteredToContextId.GetHashCode();
      if (eventDefinitionId_ != null) hash ^= EventDefinitionId.GetHashCode();
      if (DEPRECATEDRegisteredToContextId.Length != 0) hash ^= DEPRECATEDRegisteredToContextId.GetHashCode();
      if (DEPRECATEDEventDefinitionId.Length != 0) hash ^= DEPRECATEDEventDefinitionId.GetHashCode();
      if (DEPRECATEDIsGlobal != false) hash ^= DEPRECATEDIsGlobal.GetHashCode();
      if (DEPRECATEDIsBuiltIn != false) hash ^= DEPRECATEDIsBuiltIn.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DEPRECATEDRegisteredToContextId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(DEPRECATEDRegisteredToContextId);
      }
      if (DEPRECATEDEventDefinitionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(DEPRECATEDEventDefinitionId);
      }
      if (DEPRECATEDIsGlobal != false) {
        output.WriteRawTag(24);
        output.WriteBool(DEPRECATEDIsGlobal);
      }
      if (DEPRECATEDIsBuiltIn != false) {
        output.WriteRawTag(32);
        output.WriteBool(DEPRECATEDIsBuiltIn);
      }
      if (registeredToContextId_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(RegisteredToContextId);
      }
      if (eventDefinitionId_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(EventDefinitionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DEPRECATEDRegisteredToContextId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(DEPRECATEDRegisteredToContextId);
      }
      if (DEPRECATEDEventDefinitionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(DEPRECATEDEventDefinitionId);
      }
      if (DEPRECATEDIsGlobal != false) {
        output.WriteRawTag(24);
        output.WriteBool(DEPRECATEDIsGlobal);
      }
      if (DEPRECATEDIsBuiltIn != false) {
        output.WriteRawTag(32);
        output.WriteBool(DEPRECATEDIsBuiltIn);
      }
      if (registeredToContextId_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(RegisteredToContextId);
      }
      if (eventDefinitionId_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(EventDefinitionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (registeredToContextId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RegisteredToContextId);
      }
      if (eventDefinitionId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EventDefinitionId);
      }
      if (DEPRECATEDRegisteredToContextId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DEPRECATEDRegisteredToContextId);
      }
      if (DEPRECATEDEventDefinitionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DEPRECATEDEventDefinitionId);
      }
      if (DEPRECATEDIsGlobal != false) {
        size += 1 + 1;
      }
      if (DEPRECATEDIsBuiltIn != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DEPRECATED_EventRegistrationData other) {
      if (other == null) {
        return;
      }
      if (other.registeredToContextId_ != null) {
        if (registeredToContextId_ == null) {
          RegisteredToContextId = new global::RecRoom.Protobuf.Core.GuidData();
        }
        RegisteredToContextId.MergeFrom(other.RegisteredToContextId);
      }
      if (other.eventDefinitionId_ != null) {
        if (eventDefinitionId_ == null) {
          EventDefinitionId = new global::RecRoom.Protobuf.Core.GuidData();
        }
        EventDefinitionId.MergeFrom(other.EventDefinitionId);
      }
      if (other.DEPRECATEDRegisteredToContextId.Length != 0) {
        DEPRECATEDRegisteredToContextId = other.DEPRECATEDRegisteredToContextId;
      }
      if (other.DEPRECATEDEventDefinitionId.Length != 0) {
        DEPRECATEDEventDefinitionId = other.DEPRECATEDEventDefinitionId;
      }
      if (other.DEPRECATEDIsGlobal != false) {
        DEPRECATEDIsGlobal = other.DEPRECATEDIsGlobal;
      }
      if (other.DEPRECATEDIsBuiltIn != false) {
        DEPRECATEDIsBuiltIn = other.DEPRECATEDIsBuiltIn;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DEPRECATEDRegisteredToContextId = input.ReadBytes();
            break;
          }
          case 18: {
            DEPRECATEDEventDefinitionId = input.ReadBytes();
            break;
          }
          case 24: {
            DEPRECATEDIsGlobal = input.ReadBool();
            break;
          }
          case 32: {
            DEPRECATEDIsBuiltIn = input.ReadBool();
            break;
          }
          case 42: {
            if (registeredToContextId_ == null) {
              RegisteredToContextId = new global::RecRoom.Protobuf.Core.GuidData();
            }
            input.ReadMessage(RegisteredToContextId);
            break;
          }
          case 50: {
            if (eventDefinitionId_ == null) {
              EventDefinitionId = new global::RecRoom.Protobuf.Core.GuidData();
            }
            input.ReadMessage(EventDefinitionId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DEPRECATEDRegisteredToContextId = input.ReadBytes();
            break;
          }
          case 18: {
            DEPRECATEDEventDefinitionId = input.ReadBytes();
            break;
          }
          case 24: {
            DEPRECATEDIsGlobal = input.ReadBool();
            break;
          }
          case 32: {
            DEPRECATEDIsBuiltIn = input.ReadBool();
            break;
          }
          case 42: {
            if (registeredToContextId_ == null) {
              RegisteredToContextId = new global::RecRoom.Protobuf.Core.GuidData();
            }
            input.ReadMessage(RegisteredToContextId);
            break;
          }
          case 50: {
            if (eventDefinitionId_ == null) {
              EventDefinitionId = new global::RecRoom.Protobuf.Core.GuidData();
            }
            input.ReadMessage(EventDefinitionId);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
