// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: circuits_v2/instance_memory_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CircuitsV2.Protobuf {

  /// <summary>Holder for reflection information generated from circuits_v2/instance_memory_data.proto</summary>
  public static partial class InstanceMemoryDataReflection {

    #region Descriptor
    /// <summary>File descriptor for circuits_v2/instance_memory_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InstanceMemoryDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZjaXJjdWl0c192Mi9pbnN0YW5jZV9tZW1vcnlfZGF0YS5wcm90bxILY2ly",
            "Y3VpdHNfdjIaFGNvcmUvZ3VpZF9kYXRhLnByb3RvGiRjaXJjdWl0c192Mi9z",
            "eW1ib2xfbWVtb3J5X2RhdGEucHJvdG8i+gMKEkluc3RhbmNlTWVtb3J5RGF0",
            "YRJICg1zeW1ib2xfbWVtb3J5GAMgAygLMjEuY2lyY3VpdHNfdjIuSW5zdGFu",
            "Y2VNZW1vcnlEYXRhLlN5bWJvbE1lbW9yeUVudHJ5ElwKGERFUFJFQ0FURURf",
            "c3ltYm9sX2d1aWRfMRgBIAMoCzI6LmNpcmN1aXRzX3YyLkluc3RhbmNlTWVt",
            "b3J5RGF0YS5ERVBSRUNBVEVEU3ltYm9sR3VpZDFFbnRyeRJcChhERVBSRUNB",
            "VEVEX3N5bWJvbF9ndWlkXzIYAiADKAsyOi5jaXJjdWl0c192Mi5JbnN0YW5j",
            "ZU1lbW9yeURhdGEuREVQUkVDQVRFRFN5bWJvbEd1aWQyRW50cnkaUgoRU3lt",
            "Ym9sTWVtb3J5RW50cnkSCwoDa2V5GAEgASgJEiwKBXZhbHVlGAIgASgLMh0u",
            "Y2lyY3VpdHNfdjIuU3ltYm9sTWVtb3J5RGF0YToCOAEaPAoaREVQUkVDQVRF",
            "RFN5bWJvbEd1aWQxRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgM",
            "OgI4ARpMChpERVBSRUNBVEVEU3ltYm9sR3VpZDJFbnRyeRILCgNrZXkYASAB",
            "KAkSHQoFdmFsdWUYAiABKAsyDi5jb3JlLkd1aWREYXRhOgI4AUIWqgITQ2ly",
            "Y3VpdHNWMi5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::RecRoom.Protobuf.Core.GuidDataReflection.Descriptor, global::CircuitsV2.Protobuf.SymbolMemoryDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CircuitsV2.Protobuf.InstanceMemoryData), global::CircuitsV2.Protobuf.InstanceMemoryData.Parser, new[]{ "SymbolMemory", "DEPRECATEDSymbolGuid1", "DEPRECATEDSymbolGuid2" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class InstanceMemoryData : pb::IMessage<InstanceMemoryData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InstanceMemoryData> _parser = new pb::MessageParser<InstanceMemoryData>(() => new InstanceMemoryData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InstanceMemoryData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CircuitsV2.Protobuf.InstanceMemoryDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InstanceMemoryData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InstanceMemoryData(InstanceMemoryData other) : this() {
      symbolMemory_ = other.symbolMemory_.Clone();
      dEPRECATEDSymbolGuid1_ = other.dEPRECATEDSymbolGuid1_.Clone();
      dEPRECATEDSymbolGuid2_ = other.dEPRECATEDSymbolGuid2_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InstanceMemoryData Clone() {
      return new InstanceMemoryData(this);
    }

    /// <summary>Field number for the "symbol_memory" field.</summary>
    public const int SymbolMemoryFieldNumber = 3;
    private static readonly pbc::MapField<string, global::CircuitsV2.Protobuf.SymbolMemoryData>.Codec _map_symbolMemory_codec
        = new pbc::MapField<string, global::CircuitsV2.Protobuf.SymbolMemoryData>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::CircuitsV2.Protobuf.SymbolMemoryData.Parser), 26);
    private readonly pbc::MapField<string, global::CircuitsV2.Protobuf.SymbolMemoryData> symbolMemory_ = new pbc::MapField<string, global::CircuitsV2.Protobuf.SymbolMemoryData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::CircuitsV2.Protobuf.SymbolMemoryData> SymbolMemory {
      get { return symbolMemory_; }
    }

    /// <summary>Field number for the "DEPRECATED_symbol_guid_1" field.</summary>
    public const int DEPRECATEDSymbolGuid1FieldNumber = 1;
    private static readonly pbc::MapField<string, pb::ByteString>.Codec _map_dEPRECATEDSymbolGuid1_codec
        = new pbc::MapField<string, pb::ByteString>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForBytes(18, pb::ByteString.Empty), 10);
    private readonly pbc::MapField<string, pb::ByteString> dEPRECATEDSymbolGuid1_ = new pbc::MapField<string, pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, pb::ByteString> DEPRECATEDSymbolGuid1 {
      get { return dEPRECATEDSymbolGuid1_; }
    }

    /// <summary>Field number for the "DEPRECATED_symbol_guid_2" field.</summary>
    public const int DEPRECATEDSymbolGuid2FieldNumber = 2;
    private static readonly pbc::MapField<string, global::RecRoom.Protobuf.Core.GuidData>.Codec _map_dEPRECATEDSymbolGuid2_codec
        = new pbc::MapField<string, global::RecRoom.Protobuf.Core.GuidData>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::RecRoom.Protobuf.Core.GuidData.Parser), 18);
    private readonly pbc::MapField<string, global::RecRoom.Protobuf.Core.GuidData> dEPRECATEDSymbolGuid2_ = new pbc::MapField<string, global::RecRoom.Protobuf.Core.GuidData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::RecRoom.Protobuf.Core.GuidData> DEPRECATEDSymbolGuid2 {
      get { return dEPRECATEDSymbolGuid2_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InstanceMemoryData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InstanceMemoryData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!SymbolMemory.Equals(other.SymbolMemory)) return false;
      if (!DEPRECATEDSymbolGuid1.Equals(other.DEPRECATEDSymbolGuid1)) return false;
      if (!DEPRECATEDSymbolGuid2.Equals(other.DEPRECATEDSymbolGuid2)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= SymbolMemory.GetHashCode();
      hash ^= DEPRECATEDSymbolGuid1.GetHashCode();
      hash ^= DEPRECATEDSymbolGuid2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dEPRECATEDSymbolGuid1_.WriteTo(output, _map_dEPRECATEDSymbolGuid1_codec);
      dEPRECATEDSymbolGuid2_.WriteTo(output, _map_dEPRECATEDSymbolGuid2_codec);
      symbolMemory_.WriteTo(output, _map_symbolMemory_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dEPRECATEDSymbolGuid1_.WriteTo(ref output, _map_dEPRECATEDSymbolGuid1_codec);
      dEPRECATEDSymbolGuid2_.WriteTo(ref output, _map_dEPRECATEDSymbolGuid2_codec);
      symbolMemory_.WriteTo(ref output, _map_symbolMemory_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += symbolMemory_.CalculateSize(_map_symbolMemory_codec);
      size += dEPRECATEDSymbolGuid1_.CalculateSize(_map_dEPRECATEDSymbolGuid1_codec);
      size += dEPRECATEDSymbolGuid2_.CalculateSize(_map_dEPRECATEDSymbolGuid2_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InstanceMemoryData other) {
      if (other == null) {
        return;
      }
      symbolMemory_.Add(other.symbolMemory_);
      dEPRECATEDSymbolGuid1_.Add(other.dEPRECATEDSymbolGuid1_);
      dEPRECATEDSymbolGuid2_.Add(other.dEPRECATEDSymbolGuid2_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dEPRECATEDSymbolGuid1_.AddEntriesFrom(input, _map_dEPRECATEDSymbolGuid1_codec);
            break;
          }
          case 18: {
            dEPRECATEDSymbolGuid2_.AddEntriesFrom(input, _map_dEPRECATEDSymbolGuid2_codec);
            break;
          }
          case 26: {
            symbolMemory_.AddEntriesFrom(input, _map_symbolMemory_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dEPRECATEDSymbolGuid1_.AddEntriesFrom(ref input, _map_dEPRECATEDSymbolGuid1_codec);
            break;
          }
          case 18: {
            dEPRECATEDSymbolGuid2_.AddEntriesFrom(ref input, _map_dEPRECATEDSymbolGuid2_codec);
            break;
          }
          case 26: {
            symbolMemory_.AddEntriesFrom(ref input, _map_symbolMemory_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
