// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: circuits_v2/is_rec_room_object_of_type_node_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CircuitsV2.Protobuf {

  /// <summary>Holder for reflection information generated from circuits_v2/is_rec_room_object_of_type_node_data.proto</summary>
  public static partial class IsRecRoomObjectOfTypeNodeDataReflection {

    #region Descriptor
    /// <summary>File descriptor for circuits_v2/is_rec_room_object_of_type_node_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IsRecRoomObjectOfTypeNodeDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjZjaXJjdWl0c192Mi9pc19yZWNfcm9vbV9vYmplY3Rfb2ZfdHlwZV9ub2Rl",
            "X2RhdGEucHJvdG8SC2NpcmN1aXRzX3YyGipjaXJjdWl0cy9zdGF0aWMvZXYv",
            "Y2lyY3VpdF90eXBlX2RhdGEucHJvdG8iTwodSXNSZWNSb29tT2JqZWN0T2ZU",
            "eXBlTm9kZURhdGESLgoLdGFyZ2V0X3R5cGUYASABKAsyGS5jaXJjdWl0cy5D",
            "aXJjdWl0VHlwZURhdGFCFqoCE0NpcmN1aXRzVjIuUHJvdG9idWZiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Circuits.Static.EV.Protobuf.CircuitTypeDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CircuitsV2.Protobuf.IsRecRoomObjectOfTypeNodeData), global::CircuitsV2.Protobuf.IsRecRoomObjectOfTypeNodeData.Parser, new[]{ "TargetType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class IsRecRoomObjectOfTypeNodeData : pb::IMessage<IsRecRoomObjectOfTypeNodeData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IsRecRoomObjectOfTypeNodeData> _parser = new pb::MessageParser<IsRecRoomObjectOfTypeNodeData>(() => new IsRecRoomObjectOfTypeNodeData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IsRecRoomObjectOfTypeNodeData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CircuitsV2.Protobuf.IsRecRoomObjectOfTypeNodeDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsRecRoomObjectOfTypeNodeData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsRecRoomObjectOfTypeNodeData(IsRecRoomObjectOfTypeNodeData other) : this() {
      targetType_ = other.targetType_ != null ? other.targetType_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsRecRoomObjectOfTypeNodeData Clone() {
      return new IsRecRoomObjectOfTypeNodeData(this);
    }

    /// <summary>Field number for the "target_type" field.</summary>
    public const int TargetTypeFieldNumber = 1;
    private global::Circuits.Static.EV.Protobuf.CircuitTypeData targetType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Circuits.Static.EV.Protobuf.CircuitTypeData TargetType {
      get { return targetType_; }
      set {
        targetType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IsRecRoomObjectOfTypeNodeData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IsRecRoomObjectOfTypeNodeData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TargetType, other.TargetType)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (targetType_ != null) hash ^= TargetType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (targetType_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TargetType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (targetType_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TargetType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (targetType_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IsRecRoomObjectOfTypeNodeData other) {
      if (other == null) {
        return;
      }
      if (other.targetType_ != null) {
        if (targetType_ == null) {
          TargetType = new global::Circuits.Static.EV.Protobuf.CircuitTypeData();
        }
        TargetType.MergeFrom(other.TargetType);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (targetType_ == null) {
              TargetType = new global::Circuits.Static.EV.Protobuf.CircuitTypeData();
            }
            input.ReadMessage(TargetType);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (targetType_ == null) {
              TargetType = new global::Circuits.Static.EV.Protobuf.CircuitTypeData();
            }
            input.ReadMessage(TargetType);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
