// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: circuits_v2/studio_functions/studio_function_definition_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CircuitsV2.Protobuf {

  /// <summary>Holder for reflection information generated from circuits_v2/studio_functions/studio_function_definition_data.proto</summary>
  public static partial class StudioFunctionDefinitionDataReflection {

    #region Descriptor
    /// <summary>File descriptor for circuits_v2/studio_functions/studio_function_definition_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StudioFunctionDefinitionDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkJjaXJjdWl0c192Mi9zdHVkaW9fZnVuY3Rpb25zL3N0dWRpb19mdW5jdGlv",
            "bl9kZWZpbml0aW9uX2RhdGEucHJvdG8SC2NpcmN1aXRzX3YyGiVjaXJjdWl0",
            "cy9zaGFyZWQvYXBpL2lkXzEyOF9kYXRhLnByb3RvInoKHFN0dWRpb0Z1bmN0",
            "aW9uRGVmaW5pdGlvbkRhdGESJgoJcHJlZmFiX2lkGAEgASgLMhMuY2lyY3Vp",
            "dHMuSWQxMjhEYXRhEhMKC3ByZWZhYl9uYW1lGAIgASgJEh0KFXN0dWRpb19m",
            "dW5jdGlvbl9pbmRleBgDIAEoBUIWqgITQ2lyY3VpdHNWMi5Qcm90b2J1ZmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Circuits.Shared.Api.Protobuf.Id128DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CircuitsV2.Protobuf.StudioFunctionDefinitionData), global::CircuitsV2.Protobuf.StudioFunctionDefinitionData.Parser, new[]{ "PrefabId", "PrefabName", "StudioFunctionIndex" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StudioFunctionDefinitionData : pb::IMessage<StudioFunctionDefinitionData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StudioFunctionDefinitionData> _parser = new pb::MessageParser<StudioFunctionDefinitionData>(() => new StudioFunctionDefinitionData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StudioFunctionDefinitionData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CircuitsV2.Protobuf.StudioFunctionDefinitionDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StudioFunctionDefinitionData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StudioFunctionDefinitionData(StudioFunctionDefinitionData other) : this() {
      prefabId_ = other.prefabId_ != null ? other.prefabId_.Clone() : null;
      prefabName_ = other.prefabName_;
      studioFunctionIndex_ = other.studioFunctionIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StudioFunctionDefinitionData Clone() {
      return new StudioFunctionDefinitionData(this);
    }

    /// <summary>Field number for the "prefab_id" field.</summary>
    public const int PrefabIdFieldNumber = 1;
    private global::Circuits.Shared.Api.Protobuf.Id128Data prefabId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Circuits.Shared.Api.Protobuf.Id128Data PrefabId {
      get { return prefabId_; }
      set {
        prefabId_ = value;
      }
    }

    /// <summary>Field number for the "prefab_name" field.</summary>
    public const int PrefabNameFieldNumber = 2;
    private string prefabName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PrefabName {
      get { return prefabName_; }
      set {
        prefabName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "studio_function_index" field.</summary>
    public const int StudioFunctionIndexFieldNumber = 3;
    private int studioFunctionIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StudioFunctionIndex {
      get { return studioFunctionIndex_; }
      set {
        studioFunctionIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StudioFunctionDefinitionData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StudioFunctionDefinitionData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PrefabId, other.PrefabId)) return false;
      if (PrefabName != other.PrefabName) return false;
      if (StudioFunctionIndex != other.StudioFunctionIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (prefabId_ != null) hash ^= PrefabId.GetHashCode();
      if (PrefabName.Length != 0) hash ^= PrefabName.GetHashCode();
      if (StudioFunctionIndex != 0) hash ^= StudioFunctionIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (prefabId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PrefabId);
      }
      if (PrefabName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PrefabName);
      }
      if (StudioFunctionIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(StudioFunctionIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (prefabId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PrefabId);
      }
      if (PrefabName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PrefabName);
      }
      if (StudioFunctionIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(StudioFunctionIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (prefabId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrefabId);
      }
      if (PrefabName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PrefabName);
      }
      if (StudioFunctionIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StudioFunctionIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StudioFunctionDefinitionData other) {
      if (other == null) {
        return;
      }
      if (other.prefabId_ != null) {
        if (prefabId_ == null) {
          PrefabId = new global::Circuits.Shared.Api.Protobuf.Id128Data();
        }
        PrefabId.MergeFrom(other.PrefabId);
      }
      if (other.PrefabName.Length != 0) {
        PrefabName = other.PrefabName;
      }
      if (other.StudioFunctionIndex != 0) {
        StudioFunctionIndex = other.StudioFunctionIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (prefabId_ == null) {
              PrefabId = new global::Circuits.Shared.Api.Protobuf.Id128Data();
            }
            input.ReadMessage(PrefabId);
            break;
          }
          case 18: {
            PrefabName = input.ReadString();
            break;
          }
          case 24: {
            StudioFunctionIndex = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (prefabId_ == null) {
              PrefabId = new global::Circuits.Shared.Api.Protobuf.Id128Data();
            }
            input.ReadMessage(PrefabId);
            break;
          }
          case 18: {
            PrefabName = input.ReadString();
            break;
          }
          case 24: {
            StudioFunctionIndex = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
