// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/persistence/collision_detection_volume_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/persistence/collision_detection_volume_data.proto</summary>
  public static partial class CollisionDetectionVolumeDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/persistence/collision_detection_volume_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CollisionDetectionVolumeDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjpyZWNfcm9vbS9wZXJzaXN0ZW5jZS9jb2xsaXNpb25fZGV0ZWN0aW9uX3Zv",
            "bHVtZV9kYXRhLnByb3RvEghyZWNfcm9vbSLzAQocQ29sbGlzaW9uRGV0ZWN0",
            "aW9uVm9sdW1lRGF0YRJXChtjYXBzdWxlX2NvbGxpZGVyX2dyb3VwX2RhdGEY",
            "ASABKAsyMi5yZWNfcm9vbS5Db2xsaXNpb25EZXRlY3Rpb25Wb2x1bWVDYXBz",
            "dWxlR3JvdXBEYXRhEhYKDnRhZ3NfdG9faWdub3JlGAIgAygJEiUKHURFUFJF",
            "Q0FURURfc3luY19lbmFibGVkX3N0YXRlGAMgASgIEhwKFGltcGFjdF9kZWNh",
            "bF9lbmFibGVkGAQgASgIEh0KFW9ubHlfcnVuX29uX2F1dGhvcml0eRgFIAEo",
            "CCKNAQooQ29sbGlzaW9uRGV0ZWN0aW9uVm9sdW1lQ2Fwc3VsZUdyb3VwRGF0",
            "YRIcChRERVBSRUNBVEVEX3RoaWNrbmVzcxgBIAEoAhIXCg9udW1fc3BoZXJl",
            "Y2FzdHMYAiABKAUSKgoic3VwcG9ydF9zdGF0aW9uYXJ5X2NvbGxpc2lvbl90",
            "ZXN0cxgDIAEoCEITqgIQUmVjUm9vbS5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.CollisionDetectionVolumeData), global::RecRoom.Protobuf.CollisionDetectionVolumeData.Parser, new[]{ "CapsuleColliderGroupData", "TagsToIgnore", "DEPRECATEDSyncEnabledState", "ImpactDecalEnabled", "OnlyRunOnAuthority" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.CollisionDetectionVolumeCapsuleGroupData), global::RecRoom.Protobuf.CollisionDetectionVolumeCapsuleGroupData.Parser, new[]{ "DEPRECATEDThickness", "NumSpherecasts", "SupportStationaryCollisionTests" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CollisionDetectionVolumeData : pb::IMessage<CollisionDetectionVolumeData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollisionDetectionVolumeData> _parser = new pb::MessageParser<CollisionDetectionVolumeData>(() => new CollisionDetectionVolumeData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CollisionDetectionVolumeData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.CollisionDetectionVolumeDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionDetectionVolumeData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionDetectionVolumeData(CollisionDetectionVolumeData other) : this() {
      capsuleColliderGroupData_ = other.capsuleColliderGroupData_ != null ? other.capsuleColliderGroupData_.Clone() : null;
      tagsToIgnore_ = other.tagsToIgnore_.Clone();
      dEPRECATEDSyncEnabledState_ = other.dEPRECATEDSyncEnabledState_;
      impactDecalEnabled_ = other.impactDecalEnabled_;
      onlyRunOnAuthority_ = other.onlyRunOnAuthority_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionDetectionVolumeData Clone() {
      return new CollisionDetectionVolumeData(this);
    }

    /// <summary>Field number for the "capsule_collider_group_data" field.</summary>
    public const int CapsuleColliderGroupDataFieldNumber = 1;
    private global::RecRoom.Protobuf.CollisionDetectionVolumeCapsuleGroupData capsuleColliderGroupData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.CollisionDetectionVolumeCapsuleGroupData CapsuleColliderGroupData {
      get { return capsuleColliderGroupData_; }
      set {
        capsuleColliderGroupData_ = value;
      }
    }

    /// <summary>Field number for the "tags_to_ignore" field.</summary>
    public const int TagsToIgnoreFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_tagsToIgnore_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> tagsToIgnore_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> TagsToIgnore {
      get { return tagsToIgnore_; }
    }

    /// <summary>Field number for the "DEPRECATED_sync_enabled_state" field.</summary>
    public const int DEPRECATEDSyncEnabledStateFieldNumber = 3;
    private bool dEPRECATEDSyncEnabledState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DEPRECATEDSyncEnabledState {
      get { return dEPRECATEDSyncEnabledState_; }
      set {
        dEPRECATEDSyncEnabledState_ = value;
      }
    }

    /// <summary>Field number for the "impact_decal_enabled" field.</summary>
    public const int ImpactDecalEnabledFieldNumber = 4;
    private bool impactDecalEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ImpactDecalEnabled {
      get { return impactDecalEnabled_; }
      set {
        impactDecalEnabled_ = value;
      }
    }

    /// <summary>Field number for the "only_run_on_authority" field.</summary>
    public const int OnlyRunOnAuthorityFieldNumber = 5;
    private bool onlyRunOnAuthority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OnlyRunOnAuthority {
      get { return onlyRunOnAuthority_; }
      set {
        onlyRunOnAuthority_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CollisionDetectionVolumeData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CollisionDetectionVolumeData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CapsuleColliderGroupData, other.CapsuleColliderGroupData)) return false;
      if(!tagsToIgnore_.Equals(other.tagsToIgnore_)) return false;
      if (DEPRECATEDSyncEnabledState != other.DEPRECATEDSyncEnabledState) return false;
      if (ImpactDecalEnabled != other.ImpactDecalEnabled) return false;
      if (OnlyRunOnAuthority != other.OnlyRunOnAuthority) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (capsuleColliderGroupData_ != null) hash ^= CapsuleColliderGroupData.GetHashCode();
      hash ^= tagsToIgnore_.GetHashCode();
      if (DEPRECATEDSyncEnabledState != false) hash ^= DEPRECATEDSyncEnabledState.GetHashCode();
      if (ImpactDecalEnabled != false) hash ^= ImpactDecalEnabled.GetHashCode();
      if (OnlyRunOnAuthority != false) hash ^= OnlyRunOnAuthority.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (capsuleColliderGroupData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CapsuleColliderGroupData);
      }
      tagsToIgnore_.WriteTo(output, _repeated_tagsToIgnore_codec);
      if (DEPRECATEDSyncEnabledState != false) {
        output.WriteRawTag(24);
        output.WriteBool(DEPRECATEDSyncEnabledState);
      }
      if (ImpactDecalEnabled != false) {
        output.WriteRawTag(32);
        output.WriteBool(ImpactDecalEnabled);
      }
      if (OnlyRunOnAuthority != false) {
        output.WriteRawTag(40);
        output.WriteBool(OnlyRunOnAuthority);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (capsuleColliderGroupData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CapsuleColliderGroupData);
      }
      tagsToIgnore_.WriteTo(ref output, _repeated_tagsToIgnore_codec);
      if (DEPRECATEDSyncEnabledState != false) {
        output.WriteRawTag(24);
        output.WriteBool(DEPRECATEDSyncEnabledState);
      }
      if (ImpactDecalEnabled != false) {
        output.WriteRawTag(32);
        output.WriteBool(ImpactDecalEnabled);
      }
      if (OnlyRunOnAuthority != false) {
        output.WriteRawTag(40);
        output.WriteBool(OnlyRunOnAuthority);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (capsuleColliderGroupData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CapsuleColliderGroupData);
      }
      size += tagsToIgnore_.CalculateSize(_repeated_tagsToIgnore_codec);
      if (DEPRECATEDSyncEnabledState != false) {
        size += 1 + 1;
      }
      if (ImpactDecalEnabled != false) {
        size += 1 + 1;
      }
      if (OnlyRunOnAuthority != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CollisionDetectionVolumeData other) {
      if (other == null) {
        return;
      }
      if (other.capsuleColliderGroupData_ != null) {
        if (capsuleColliderGroupData_ == null) {
          CapsuleColliderGroupData = new global::RecRoom.Protobuf.CollisionDetectionVolumeCapsuleGroupData();
        }
        CapsuleColliderGroupData.MergeFrom(other.CapsuleColliderGroupData);
      }
      tagsToIgnore_.Add(other.tagsToIgnore_);
      if (other.DEPRECATEDSyncEnabledState != false) {
        DEPRECATEDSyncEnabledState = other.DEPRECATEDSyncEnabledState;
      }
      if (other.ImpactDecalEnabled != false) {
        ImpactDecalEnabled = other.ImpactDecalEnabled;
      }
      if (other.OnlyRunOnAuthority != false) {
        OnlyRunOnAuthority = other.OnlyRunOnAuthority;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (capsuleColliderGroupData_ == null) {
              CapsuleColliderGroupData = new global::RecRoom.Protobuf.CollisionDetectionVolumeCapsuleGroupData();
            }
            input.ReadMessage(CapsuleColliderGroupData);
            break;
          }
          case 18: {
            tagsToIgnore_.AddEntriesFrom(input, _repeated_tagsToIgnore_codec);
            break;
          }
          case 24: {
            DEPRECATEDSyncEnabledState = input.ReadBool();
            break;
          }
          case 32: {
            ImpactDecalEnabled = input.ReadBool();
            break;
          }
          case 40: {
            OnlyRunOnAuthority = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (capsuleColliderGroupData_ == null) {
              CapsuleColliderGroupData = new global::RecRoom.Protobuf.CollisionDetectionVolumeCapsuleGroupData();
            }
            input.ReadMessage(CapsuleColliderGroupData);
            break;
          }
          case 18: {
            tagsToIgnore_.AddEntriesFrom(ref input, _repeated_tagsToIgnore_codec);
            break;
          }
          case 24: {
            DEPRECATEDSyncEnabledState = input.ReadBool();
            break;
          }
          case 32: {
            ImpactDecalEnabled = input.ReadBool();
            break;
          }
          case 40: {
            OnlyRunOnAuthority = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CollisionDetectionVolumeCapsuleGroupData : pb::IMessage<CollisionDetectionVolumeCapsuleGroupData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollisionDetectionVolumeCapsuleGroupData> _parser = new pb::MessageParser<CollisionDetectionVolumeCapsuleGroupData>(() => new CollisionDetectionVolumeCapsuleGroupData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CollisionDetectionVolumeCapsuleGroupData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.CollisionDetectionVolumeDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionDetectionVolumeCapsuleGroupData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionDetectionVolumeCapsuleGroupData(CollisionDetectionVolumeCapsuleGroupData other) : this() {
      dEPRECATEDThickness_ = other.dEPRECATEDThickness_;
      numSpherecasts_ = other.numSpherecasts_;
      supportStationaryCollisionTests_ = other.supportStationaryCollisionTests_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollisionDetectionVolumeCapsuleGroupData Clone() {
      return new CollisionDetectionVolumeCapsuleGroupData(this);
    }

    /// <summary>Field number for the "DEPRECATED_thickness" field.</summary>
    public const int DEPRECATEDThicknessFieldNumber = 1;
    private float dEPRECATEDThickness_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DEPRECATEDThickness {
      get { return dEPRECATEDThickness_; }
      set {
        dEPRECATEDThickness_ = value;
      }
    }

    /// <summary>Field number for the "num_spherecasts" field.</summary>
    public const int NumSpherecastsFieldNumber = 2;
    private int numSpherecasts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumSpherecasts {
      get { return numSpherecasts_; }
      set {
        numSpherecasts_ = value;
      }
    }

    /// <summary>Field number for the "support_stationary_collision_tests" field.</summary>
    public const int SupportStationaryCollisionTestsFieldNumber = 3;
    private bool supportStationaryCollisionTests_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SupportStationaryCollisionTests {
      get { return supportStationaryCollisionTests_; }
      set {
        supportStationaryCollisionTests_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CollisionDetectionVolumeCapsuleGroupData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CollisionDetectionVolumeCapsuleGroupData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DEPRECATEDThickness, other.DEPRECATEDThickness)) return false;
      if (NumSpherecasts != other.NumSpherecasts) return false;
      if (SupportStationaryCollisionTests != other.SupportStationaryCollisionTests) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DEPRECATEDThickness != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DEPRECATEDThickness);
      if (NumSpherecasts != 0) hash ^= NumSpherecasts.GetHashCode();
      if (SupportStationaryCollisionTests != false) hash ^= SupportStationaryCollisionTests.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DEPRECATEDThickness != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(DEPRECATEDThickness);
      }
      if (NumSpherecasts != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumSpherecasts);
      }
      if (SupportStationaryCollisionTests != false) {
        output.WriteRawTag(24);
        output.WriteBool(SupportStationaryCollisionTests);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DEPRECATEDThickness != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(DEPRECATEDThickness);
      }
      if (NumSpherecasts != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumSpherecasts);
      }
      if (SupportStationaryCollisionTests != false) {
        output.WriteRawTag(24);
        output.WriteBool(SupportStationaryCollisionTests);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DEPRECATEDThickness != 0F) {
        size += 1 + 4;
      }
      if (NumSpherecasts != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumSpherecasts);
      }
      if (SupportStationaryCollisionTests != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CollisionDetectionVolumeCapsuleGroupData other) {
      if (other == null) {
        return;
      }
      if (other.DEPRECATEDThickness != 0F) {
        DEPRECATEDThickness = other.DEPRECATEDThickness;
      }
      if (other.NumSpherecasts != 0) {
        NumSpherecasts = other.NumSpherecasts;
      }
      if (other.SupportStationaryCollisionTests != false) {
        SupportStationaryCollisionTests = other.SupportStationaryCollisionTests;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            DEPRECATEDThickness = input.ReadFloat();
            break;
          }
          case 16: {
            NumSpherecasts = input.ReadInt32();
            break;
          }
          case 24: {
            SupportStationaryCollisionTests = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            DEPRECATEDThickness = input.ReadFloat();
            break;
          }
          case 16: {
            NumSpherecasts = input.ReadInt32();
            break;
          }
          case 24: {
            SupportStationaryCollisionTests = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
