// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/persistence/deprecated/DEPRECATED_room_persistence_version.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/persistence/deprecated/DEPRECATED_room_persistence_version.proto</summary>
  public static partial class DEPRECATEDRoomPersistenceVersionReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/persistence/deprecated/DEPRECATED_room_persistence_version.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DEPRECATEDRoomPersistenceVersionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CklyZWNfcm9vbS9wZXJzaXN0ZW5jZS9kZXByZWNhdGVkL0RFUFJFQ0FURURf",
            "cm9vbV9wZXJzaXN0ZW5jZV92ZXJzaW9uLnByb3RvEghyZWNfcm9vbSquCQoh",
            "REVQUkVDQVRFRF9Sb29tUGVyc2lzdGVuY2VWZXJzaW9uEh8KG1YwTmV3Um9v",
            "bVBlcnNpc3RlbmNlVmVyc2lvbhAAEg0KCVYxSW5pdGlhbBABEhwKGFYyRXh0",
            "cnVzaW9uc0NlbnRlck9mTWFzcxACEhwKGFYzUGVyc2lzdGVudEhvc3RTZXR0",
            "aW5ncxADEhYKElY0UmFkaW9QZXJzaXN0ZW5jZRAEEhsKF1Y1RXh0cnVzaW9u",
            "c1BoeXNpY3NNb2RlEAUSGAoUVjZDdXN0b21HYW1lU2V0dGluZ3MQBhIWChJW",
            "N05ld1NhbmRib3hCdXR0b24QBxIcChhWOENpcmN1aXRDaGlwT3JpZW50YXRp",
            "b24QCBIWChJWOU5ld1RyaWdnZXJWb2x1bWUQCRIQCgxWMTBSb29tUm9sZXMQ",
            "ChIgChxWMTFTdWJleHRydXNpb25zUGVyc2lzdGVkSWRzEAsSFgoSVjEyRXZl",
            "cnl0aGluZ0FSb29tEAwSGgoWVjEzQ3JlYXRpb25PYmplY3RBZGRlZBANEhoK",
            "FlYxNEludmVudGlvblBpZWNlQWRkZWQQDhIdChlWMTVHYW1lQ29uZmlndXJh",
            "dGlvbkFkZGVkEA8SGQoVVjE2RXJhc2VyTWFya2Vyc0ZpeGVkEBASFQoRVjE3",
            "R3JhYmJhYmxlQWRkZWQQERIdChlWMThNYW51YWxTcGF3blBvaW50c0FkZGVk",
            "EBISIgoeVjE5U3R1bnRSdW5uZXJCdXR0b25Ob2RlQ2hhbmdlEBMSFwoTVjIw",
            "R2FtZVJvbGVzSW5DaGlwcxAUEiIKHlYyMVBsYXllckF0dHJhY3RvckNvbmZp",
            "Z3VyYWJsZRAVEhkKFVYyMkF1dG9zYXZlVmFsaWRhdGlvbhAWEiUKIVYyM1Ry",
            "aWdnZXJWb2x1bWVOb1NoYXBlQ29udGFpbmVycxAXEiwKKFYyNEdhZGdldFZp",
            "c2liaWxpdHlNb3ZlZFRvU3Vicm9vbVNldHRpbmcQGBITCg9WMjVSb29tS2V5",
            "c0JldGEQGRIbChdWMjZEaXJlY3Rpb25hbFZvaWNlQ2hhdBAaEh4KGlYyN0p1",
            "bmlvckVuYWJsZWRPYmplY3RGbGFnEBsSFAoQVjI4U2Z4UGxheUZvckFsbBAc",
            "EhoKFlYyOVVWTWFuaXB1bGF0aW9uQWRkZWQQHRIWChJWMzBIb21lVmFsdWVz",
            "QWRkZWQQHhIfChtWMzFTZWF0Q29sbGlzaW9uVG9nZ2xlQWRkZWQQHxIfChtW",
            "MzJTdG9yaW5nUm90YXRpb25Bc1ZlY3RvcjQQIBIXChNWMzNMaWdodFZhbHVl",
            "c0Zsb2F0ECESHgoaVjM0T3B0aW1pemVDb2xsaWRlcnNUb2dnbGUQIhIcChhW",
            "MzVBdWRpb1BsYXllclByb3BlcnRpZXMQIxImCiJWMzZCYWNrcGFja1Rvb2xz",
            "Rm9yYmlkZGVuSW5TcGF3bmVyECQSGgoWVjM3VG9vbEhhbmRlZG5lc3NBZGRl",
            "ZBAlEhwKGFYzOFByb2plY3RpbGVTcHJlYWRGbG9hdBAmEiAKHExhdGVzdFJv",
            "b21QZXJzaXN0ZW5jZVZlcnNpb24QJhoCEAFCE6oCEFJlY1Jvb20uUHJvdG9i",
            "dWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RecRoom.Protobuf.DEPRECATED_RoomPersistenceVersion), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum DEPRECATED_RoomPersistenceVersion {
    [pbr::OriginalName("V0NewRoomPersistenceVersion")] V0NewRoomPersistenceVersion = 0,
    [pbr::OriginalName("V1Initial")] V1Initial = 1,
    [pbr::OriginalName("V2ExtrusionsCenterOfMass")] V2ExtrusionsCenterOfMass = 2,
    [pbr::OriginalName("V3PersistentHostSettings")] V3PersistentHostSettings = 3,
    [pbr::OriginalName("V4RadioPersistence")] V4RadioPersistence = 4,
    [pbr::OriginalName("V5ExtrusionsPhysicsMode")] V5ExtrusionsPhysicsMode = 5,
    [pbr::OriginalName("V6CustomGameSettings")] V6CustomGameSettings = 6,
    [pbr::OriginalName("V7NewSandboxButton")] V7NewSandboxButton = 7,
    [pbr::OriginalName("V8CircuitChipOrientation")] V8CircuitChipOrientation = 8,
    [pbr::OriginalName("V9NewTriggerVolume")] V9NewTriggerVolume = 9,
    [pbr::OriginalName("V10RoomRoles")] V10RoomRoles = 10,
    [pbr::OriginalName("V11SubextrusionsPersistedIds")] V11SubextrusionsPersistedIds = 11,
    [pbr::OriginalName("V12EverythingARoom")] V12EverythingAroom = 12,
    [pbr::OriginalName("V13CreationObjectAdded")] V13CreationObjectAdded = 13,
    [pbr::OriginalName("V14InventionPieceAdded")] V14InventionPieceAdded = 14,
    [pbr::OriginalName("V15GameConfigurationAdded")] V15GameConfigurationAdded = 15,
    [pbr::OriginalName("V16EraserMarkersFixed")] V16EraserMarkersFixed = 16,
    [pbr::OriginalName("V17GrabbableAdded")] V17GrabbableAdded = 17,
    [pbr::OriginalName("V18ManualSpawnPointsAdded")] V18ManualSpawnPointsAdded = 18,
    [pbr::OriginalName("V19StuntRunnerButtonNodeChange")] V19StuntRunnerButtonNodeChange = 19,
    [pbr::OriginalName("V20GameRolesInChips")] V20GameRolesInChips = 20,
    [pbr::OriginalName("V21PlayerAttractorConfigurable")] V21PlayerAttractorConfigurable = 21,
    [pbr::OriginalName("V22AutosaveValidation")] V22AutosaveValidation = 22,
    [pbr::OriginalName("V23TriggerVolumeNoShapeContainers")] V23TriggerVolumeNoShapeContainers = 23,
    [pbr::OriginalName("V24GadgetVisibilityMovedToSubroomSetting")] V24GadgetVisibilityMovedToSubroomSetting = 24,
    [pbr::OriginalName("V25RoomKeysBeta")] V25RoomKeysBeta = 25,
    [pbr::OriginalName("V26DirectionalVoiceChat")] V26DirectionalVoiceChat = 26,
    [pbr::OriginalName("V27JuniorEnabledObjectFlag")] V27JuniorEnabledObjectFlag = 27,
    [pbr::OriginalName("V28SfxPlayForAll")] V28SfxPlayForAll = 28,
    [pbr::OriginalName("V29UVManipulationAdded")] V29UvmanipulationAdded = 29,
    [pbr::OriginalName("V30HomeValuesAdded")] V30HomeValuesAdded = 30,
    [pbr::OriginalName("V31SeatCollisionToggleAdded")] V31SeatCollisionToggleAdded = 31,
    [pbr::OriginalName("V32StoringRotationAsVector4")] V32StoringRotationAsVector4 = 32,
    [pbr::OriginalName("V33LightValuesFloat")] V33LightValuesFloat = 33,
    [pbr::OriginalName("V34OptimizeCollidersToggle")] V34OptimizeCollidersToggle = 34,
    [pbr::OriginalName("V35AudioPlayerProperties")] V35AudioPlayerProperties = 35,
    [pbr::OriginalName("V36BackpackToolsForbiddenInSpawner")] V36BackpackToolsForbiddenInSpawner = 36,
    [pbr::OriginalName("V37ToolHandednessAdded")] V37ToolHandednessAdded = 37,
    [pbr::OriginalName("V38ProjectileSpreadFloat")] V38ProjectileSpreadFloat = 38,
    [pbr::OriginalName("LatestRoomPersistenceVersion", PreferredAlias = false)] LatestRoomPersistenceVersion = 38,
  }

  #endregion

}

#endregion Designer generated code
