// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/persistence/deprecated/DEPRECATED_sandbox_settings_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/persistence/deprecated/DEPRECATED_sandbox_settings_data.proto</summary>
  public static partial class DEPRECATEDSandboxSettingsDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/persistence/deprecated/DEPRECATED_sandbox_settings_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DEPRECATEDSandboxSettingsDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkZyZWNfcm9vbS9wZXJzaXN0ZW5jZS9kZXByZWNhdGVkL0RFUFJFQ0FURURf",
            "c2FuZGJveF9zZXR0aW5nc19kYXRhLnByb3RvEghyZWNfcm9vbSJwCh5ERVBS",
            "RUNBVEVEX1NhbmRib3hTZXR0aW5nc0RhdGESJwofREVQUkVDQVRFRF9saW1p",
            "dF90ZWxlcG9ydF9zcGVlZBgBIAEoCBIlCh1ERVBSRUNBVEVEX3RpbWVfbGlt",
            "aXRfc2Vjb25kcxgCIAEoBUITqgIQUmVjUm9vbS5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.DEPRECATED_SandboxSettingsData), global::RecRoom.Protobuf.DEPRECATED_SandboxSettingsData.Parser, new[]{ "DEPRECATEDLimitTeleportSpeed", "DEPRECATEDTimeLimitSeconds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DEPRECATED_SandboxSettingsData : pb::IMessage<DEPRECATED_SandboxSettingsData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DEPRECATED_SandboxSettingsData> _parser = new pb::MessageParser<DEPRECATED_SandboxSettingsData>(() => new DEPRECATED_SandboxSettingsData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DEPRECATED_SandboxSettingsData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.DEPRECATEDSandboxSettingsDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DEPRECATED_SandboxSettingsData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DEPRECATED_SandboxSettingsData(DEPRECATED_SandboxSettingsData other) : this() {
      dEPRECATEDLimitTeleportSpeed_ = other.dEPRECATEDLimitTeleportSpeed_;
      dEPRECATEDTimeLimitSeconds_ = other.dEPRECATEDTimeLimitSeconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DEPRECATED_SandboxSettingsData Clone() {
      return new DEPRECATED_SandboxSettingsData(this);
    }

    /// <summary>Field number for the "DEPRECATED_limit_teleport_speed" field.</summary>
    public const int DEPRECATEDLimitTeleportSpeedFieldNumber = 1;
    private bool dEPRECATEDLimitTeleportSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DEPRECATEDLimitTeleportSpeed {
      get { return dEPRECATEDLimitTeleportSpeed_; }
      set {
        dEPRECATEDLimitTeleportSpeed_ = value;
      }
    }

    /// <summary>Field number for the "DEPRECATED_time_limit_seconds" field.</summary>
    public const int DEPRECATEDTimeLimitSecondsFieldNumber = 2;
    private int dEPRECATEDTimeLimitSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DEPRECATEDTimeLimitSeconds {
      get { return dEPRECATEDTimeLimitSeconds_; }
      set {
        dEPRECATEDTimeLimitSeconds_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DEPRECATED_SandboxSettingsData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DEPRECATED_SandboxSettingsData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DEPRECATEDLimitTeleportSpeed != other.DEPRECATEDLimitTeleportSpeed) return false;
      if (DEPRECATEDTimeLimitSeconds != other.DEPRECATEDTimeLimitSeconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DEPRECATEDLimitTeleportSpeed != false) hash ^= DEPRECATEDLimitTeleportSpeed.GetHashCode();
      if (DEPRECATEDTimeLimitSeconds != 0) hash ^= DEPRECATEDTimeLimitSeconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DEPRECATEDLimitTeleportSpeed != false) {
        output.WriteRawTag(8);
        output.WriteBool(DEPRECATEDLimitTeleportSpeed);
      }
      if (DEPRECATEDTimeLimitSeconds != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DEPRECATEDTimeLimitSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DEPRECATEDLimitTeleportSpeed != false) {
        output.WriteRawTag(8);
        output.WriteBool(DEPRECATEDLimitTeleportSpeed);
      }
      if (DEPRECATEDTimeLimitSeconds != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DEPRECATEDTimeLimitSeconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DEPRECATEDLimitTeleportSpeed != false) {
        size += 1 + 1;
      }
      if (DEPRECATEDTimeLimitSeconds != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DEPRECATEDTimeLimitSeconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DEPRECATED_SandboxSettingsData other) {
      if (other == null) {
        return;
      }
      if (other.DEPRECATEDLimitTeleportSpeed != false) {
        DEPRECATEDLimitTeleportSpeed = other.DEPRECATEDLimitTeleportSpeed;
      }
      if (other.DEPRECATEDTimeLimitSeconds != 0) {
        DEPRECATEDTimeLimitSeconds = other.DEPRECATEDTimeLimitSeconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DEPRECATEDLimitTeleportSpeed = input.ReadBool();
            break;
          }
          case 16: {
            DEPRECATEDTimeLimitSeconds = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DEPRECATEDLimitTeleportSpeed = input.ReadBool();
            break;
          }
          case 16: {
            DEPRECATEDTimeLimitSeconds = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
