// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/game_configuration/game_combat_down_but_not_out_configuration_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/game_configuration/game_combat_down_but_not_out_configuration_data.proto</summary>
  public static partial class GameCombatDownButNotOutConfigurationDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/game_configuration/game_combat_down_but_not_out_configuration_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameCombatDownButNotOutConfigurationDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ClFyZWNfcm9vbS9nYW1lX2NvbmZpZ3VyYXRpb24vZ2FtZV9jb21iYXRfZG93",
            "bl9idXRfbm90X291dF9jb25maWd1cmF0aW9uX2RhdGEucHJvdG8SCHJlY19y",
            "b29tIogBCihHYW1lQ29tYmF0RG93bkJ1dE5vdE91dENvbmZpZ3VyYXRpb25E",
            "YXRhEhwKFERFUFJFQ0FURURfbWF4X3ZhbHVlGAEgASgCEh4KFm1heF9kZXBs",
            "ZXRpb25fZHVyYXRpb24YAiABKAISHgoWaW52aW5jaWJpbGl0eV9kdXJhdGlv",
            "bhgDIAEoAkITqgIQUmVjUm9vbS5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.GameCombatDownButNotOutConfigurationData), global::RecRoom.Protobuf.GameCombatDownButNotOutConfigurationData.Parser, new[]{ "DEPRECATEDMaxValue", "MaxDepletionDuration", "InvincibilityDuration" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GameCombatDownButNotOutConfigurationData : pb::IMessage<GameCombatDownButNotOutConfigurationData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameCombatDownButNotOutConfigurationData> _parser = new pb::MessageParser<GameCombatDownButNotOutConfigurationData>(() => new GameCombatDownButNotOutConfigurationData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameCombatDownButNotOutConfigurationData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.GameCombatDownButNotOutConfigurationDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameCombatDownButNotOutConfigurationData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameCombatDownButNotOutConfigurationData(GameCombatDownButNotOutConfigurationData other) : this() {
      dEPRECATEDMaxValue_ = other.dEPRECATEDMaxValue_;
      maxDepletionDuration_ = other.maxDepletionDuration_;
      invincibilityDuration_ = other.invincibilityDuration_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameCombatDownButNotOutConfigurationData Clone() {
      return new GameCombatDownButNotOutConfigurationData(this);
    }

    /// <summary>Field number for the "DEPRECATED_max_value" field.</summary>
    public const int DEPRECATEDMaxValueFieldNumber = 1;
    private float dEPRECATEDMaxValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DEPRECATEDMaxValue {
      get { return dEPRECATEDMaxValue_; }
      set {
        dEPRECATEDMaxValue_ = value;
      }
    }

    /// <summary>Field number for the "max_depletion_duration" field.</summary>
    public const int MaxDepletionDurationFieldNumber = 2;
    private float maxDepletionDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxDepletionDuration {
      get { return maxDepletionDuration_; }
      set {
        maxDepletionDuration_ = value;
      }
    }

    /// <summary>Field number for the "invincibility_duration" field.</summary>
    public const int InvincibilityDurationFieldNumber = 3;
    private float invincibilityDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float InvincibilityDuration {
      get { return invincibilityDuration_; }
      set {
        invincibilityDuration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameCombatDownButNotOutConfigurationData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameCombatDownButNotOutConfigurationData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DEPRECATEDMaxValue, other.DEPRECATEDMaxValue)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxDepletionDuration, other.MaxDepletionDuration)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(InvincibilityDuration, other.InvincibilityDuration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DEPRECATEDMaxValue != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DEPRECATEDMaxValue);
      if (MaxDepletionDuration != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxDepletionDuration);
      if (InvincibilityDuration != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(InvincibilityDuration);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DEPRECATEDMaxValue != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(DEPRECATEDMaxValue);
      }
      if (MaxDepletionDuration != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MaxDepletionDuration);
      }
      if (InvincibilityDuration != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(InvincibilityDuration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DEPRECATEDMaxValue != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(DEPRECATEDMaxValue);
      }
      if (MaxDepletionDuration != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MaxDepletionDuration);
      }
      if (InvincibilityDuration != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(InvincibilityDuration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DEPRECATEDMaxValue != 0F) {
        size += 1 + 4;
      }
      if (MaxDepletionDuration != 0F) {
        size += 1 + 4;
      }
      if (InvincibilityDuration != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameCombatDownButNotOutConfigurationData other) {
      if (other == null) {
        return;
      }
      if (other.DEPRECATEDMaxValue != 0F) {
        DEPRECATEDMaxValue = other.DEPRECATEDMaxValue;
      }
      if (other.MaxDepletionDuration != 0F) {
        MaxDepletionDuration = other.MaxDepletionDuration;
      }
      if (other.InvincibilityDuration != 0F) {
        InvincibilityDuration = other.InvincibilityDuration;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            DEPRECATEDMaxValue = input.ReadFloat();
            break;
          }
          case 21: {
            MaxDepletionDuration = input.ReadFloat();
            break;
          }
          case 29: {
            InvincibilityDuration = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            DEPRECATEDMaxValue = input.ReadFloat();
            break;
          }
          case 21: {
            MaxDepletionDuration = input.ReadFloat();
            break;
          }
          case 29: {
            InvincibilityDuration = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
