// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/game_configuration/game_combat_respawn_configuration_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/game_configuration/game_combat_respawn_configuration_data.proto</summary>
  public static partial class GameCombatRespawnConfigurationDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/game_configuration/game_combat_respawn_configuration_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameCombatRespawnConfigurationDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkhyZWNfcm9vbS9nYW1lX2NvbmZpZ3VyYXRpb24vZ2FtZV9jb21iYXRfcmVz",
            "cGF3bl9jb25maWd1cmF0aW9uX2RhdGEucHJvdG8SCHJlY19yb29tIosBCiJH",
            "YW1lQ29tYmF0UmVzcGF3bkNvbmZpZ3VyYXRpb25EYXRhEhoKEmF1dG9fcmVz",
            "cGF3bl9kZWxheRgBIAEoAhIhChlyZXN0b3JlX2hlYWx0aF9vbl9yZXNwYXdu",
            "GAIgASgIEiYKHnJlc3Bhd25faW52aW5jaWJpbGl0eV9kdXJhdGlvbhgDIAEo",
            "AkITqgIQUmVjUm9vbS5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.GameCombatRespawnConfigurationData), global::RecRoom.Protobuf.GameCombatRespawnConfigurationData.Parser, new[]{ "AutoRespawnDelay", "RestoreHealthOnRespawn", "RespawnInvincibilityDuration" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GameCombatRespawnConfigurationData : pb::IMessage<GameCombatRespawnConfigurationData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameCombatRespawnConfigurationData> _parser = new pb::MessageParser<GameCombatRespawnConfigurationData>(() => new GameCombatRespawnConfigurationData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameCombatRespawnConfigurationData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.GameCombatRespawnConfigurationDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameCombatRespawnConfigurationData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameCombatRespawnConfigurationData(GameCombatRespawnConfigurationData other) : this() {
      autoRespawnDelay_ = other.autoRespawnDelay_;
      restoreHealthOnRespawn_ = other.restoreHealthOnRespawn_;
      respawnInvincibilityDuration_ = other.respawnInvincibilityDuration_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameCombatRespawnConfigurationData Clone() {
      return new GameCombatRespawnConfigurationData(this);
    }

    /// <summary>Field number for the "auto_respawn_delay" field.</summary>
    public const int AutoRespawnDelayFieldNumber = 1;
    private float autoRespawnDelay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AutoRespawnDelay {
      get { return autoRespawnDelay_; }
      set {
        autoRespawnDelay_ = value;
      }
    }

    /// <summary>Field number for the "restore_health_on_respawn" field.</summary>
    public const int RestoreHealthOnRespawnFieldNumber = 2;
    private bool restoreHealthOnRespawn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RestoreHealthOnRespawn {
      get { return restoreHealthOnRespawn_; }
      set {
        restoreHealthOnRespawn_ = value;
      }
    }

    /// <summary>Field number for the "respawn_invincibility_duration" field.</summary>
    public const int RespawnInvincibilityDurationFieldNumber = 3;
    private float respawnInvincibilityDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RespawnInvincibilityDuration {
      get { return respawnInvincibilityDuration_; }
      set {
        respawnInvincibilityDuration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameCombatRespawnConfigurationData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameCombatRespawnConfigurationData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AutoRespawnDelay, other.AutoRespawnDelay)) return false;
      if (RestoreHealthOnRespawn != other.RestoreHealthOnRespawn) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RespawnInvincibilityDuration, other.RespawnInvincibilityDuration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AutoRespawnDelay != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AutoRespawnDelay);
      if (RestoreHealthOnRespawn != false) hash ^= RestoreHealthOnRespawn.GetHashCode();
      if (RespawnInvincibilityDuration != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RespawnInvincibilityDuration);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AutoRespawnDelay != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(AutoRespawnDelay);
      }
      if (RestoreHealthOnRespawn != false) {
        output.WriteRawTag(16);
        output.WriteBool(RestoreHealthOnRespawn);
      }
      if (RespawnInvincibilityDuration != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(RespawnInvincibilityDuration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AutoRespawnDelay != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(AutoRespawnDelay);
      }
      if (RestoreHealthOnRespawn != false) {
        output.WriteRawTag(16);
        output.WriteBool(RestoreHealthOnRespawn);
      }
      if (RespawnInvincibilityDuration != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(RespawnInvincibilityDuration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AutoRespawnDelay != 0F) {
        size += 1 + 4;
      }
      if (RestoreHealthOnRespawn != false) {
        size += 1 + 1;
      }
      if (RespawnInvincibilityDuration != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameCombatRespawnConfigurationData other) {
      if (other == null) {
        return;
      }
      if (other.AutoRespawnDelay != 0F) {
        AutoRespawnDelay = other.AutoRespawnDelay;
      }
      if (other.RestoreHealthOnRespawn != false) {
        RestoreHealthOnRespawn = other.RestoreHealthOnRespawn;
      }
      if (other.RespawnInvincibilityDuration != 0F) {
        RespawnInvincibilityDuration = other.RespawnInvincibilityDuration;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            AutoRespawnDelay = input.ReadFloat();
            break;
          }
          case 16: {
            RestoreHealthOnRespawn = input.ReadBool();
            break;
          }
          case 29: {
            RespawnInvincibilityDuration = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            AutoRespawnDelay = input.ReadFloat();
            break;
          }
          case 16: {
            RestoreHealthOnRespawn = input.ReadBool();
            break;
          }
          case 29: {
            RespawnInvincibilityDuration = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
