// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/persistence/mannequin_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/persistence/mannequin_data.proto</summary>
  public static partial class MannequinDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/persistence/mannequin_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MannequinDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilyZWNfcm9vbS9wZXJzaXN0ZW5jZS9tYW5uZXF1aW5fZGF0YS5wcm90bxII",
            "cmVjX3Jvb20aJnJlY19yb29tL3BlcnNpc3RlbmNlL2F2YXRhcl9kYXRhLnBy",
            "b3RvGhdjb3JlL3ZlY3RvcjNfZGF0YS5wcm90byKmAgoNTWFubmVxdWluRGF0",
            "YRIpCgthdmF0YXJfZGF0YRgBIAEoCzIULnJlY19yb29tLkF2YXRhckRhdGES",
            "EwoLaWRsZV9zdGFuY2UYAiABKAUSJAocaWRsZV9zdGFuY2VfbGVmdF9yaWdo",
            "dF9ibGVuZBgDIAEoAhISCgpwb3N0dXJlX2lkGAQgASgFEiEKGWxlZnRfaGFu",
            "ZF9wb3N0dXJlX2VuYWJsZWQYBSABKAgSIgoacmlnaHRfaGFuZF9wb3N0dXJl",
            "X2VuYWJsZWQYBiABKAgSKwoQcG9zdHVyZV9yb3RhdGlvbhgHIAEoCzIRLmNv",
            "cmUuVmVjdG9yM0RhdGESFgoObWlycm9yX3Bvc3R1cmUYCCABKAgSDwoHZmFj",
            "ZV9pZBgJIAEoBUITqgIQUmVjUm9vbS5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::RecRoom.Protobuf.AvatarDataReflection.Descriptor, global::RecRoom.Protobuf.Core.Vector3DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.MannequinData), global::RecRoom.Protobuf.MannequinData.Parser, new[]{ "AvatarData", "IdleStance", "IdleStanceLeftRightBlend", "PostureId", "LeftHandPostureEnabled", "RightHandPostureEnabled", "PostureRotation", "MirrorPosture", "FaceId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MannequinData : pb::IMessage<MannequinData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MannequinData> _parser = new pb::MessageParser<MannequinData>(() => new MannequinData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MannequinData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.MannequinDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MannequinData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MannequinData(MannequinData other) : this() {
      avatarData_ = other.avatarData_ != null ? other.avatarData_.Clone() : null;
      idleStance_ = other.idleStance_;
      idleStanceLeftRightBlend_ = other.idleStanceLeftRightBlend_;
      postureId_ = other.postureId_;
      leftHandPostureEnabled_ = other.leftHandPostureEnabled_;
      rightHandPostureEnabled_ = other.rightHandPostureEnabled_;
      postureRotation_ = other.postureRotation_ != null ? other.postureRotation_.Clone() : null;
      mirrorPosture_ = other.mirrorPosture_;
      faceId_ = other.faceId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MannequinData Clone() {
      return new MannequinData(this);
    }

    /// <summary>Field number for the "avatar_data" field.</summary>
    public const int AvatarDataFieldNumber = 1;
    private global::RecRoom.Protobuf.AvatarData avatarData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.AvatarData AvatarData {
      get { return avatarData_; }
      set {
        avatarData_ = value;
      }
    }

    /// <summary>Field number for the "idle_stance" field.</summary>
    public const int IdleStanceFieldNumber = 2;
    private int idleStance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdleStance {
      get { return idleStance_; }
      set {
        idleStance_ = value;
      }
    }

    /// <summary>Field number for the "idle_stance_left_right_blend" field.</summary>
    public const int IdleStanceLeftRightBlendFieldNumber = 3;
    private float idleStanceLeftRightBlend_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float IdleStanceLeftRightBlend {
      get { return idleStanceLeftRightBlend_; }
      set {
        idleStanceLeftRightBlend_ = value;
      }
    }

    /// <summary>Field number for the "posture_id" field.</summary>
    public const int PostureIdFieldNumber = 4;
    private int postureId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PostureId {
      get { return postureId_; }
      set {
        postureId_ = value;
      }
    }

    /// <summary>Field number for the "left_hand_posture_enabled" field.</summary>
    public const int LeftHandPostureEnabledFieldNumber = 5;
    private bool leftHandPostureEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LeftHandPostureEnabled {
      get { return leftHandPostureEnabled_; }
      set {
        leftHandPostureEnabled_ = value;
      }
    }

    /// <summary>Field number for the "right_hand_posture_enabled" field.</summary>
    public const int RightHandPostureEnabledFieldNumber = 6;
    private bool rightHandPostureEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RightHandPostureEnabled {
      get { return rightHandPostureEnabled_; }
      set {
        rightHandPostureEnabled_ = value;
      }
    }

    /// <summary>Field number for the "posture_rotation" field.</summary>
    public const int PostureRotationFieldNumber = 7;
    private global::RecRoom.Protobuf.Core.Vector3Data postureRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.Core.Vector3Data PostureRotation {
      get { return postureRotation_; }
      set {
        postureRotation_ = value;
      }
    }

    /// <summary>Field number for the "mirror_posture" field.</summary>
    public const int MirrorPostureFieldNumber = 8;
    private bool mirrorPosture_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MirrorPosture {
      get { return mirrorPosture_; }
      set {
        mirrorPosture_ = value;
      }
    }

    /// <summary>Field number for the "face_id" field.</summary>
    public const int FaceIdFieldNumber = 9;
    private int faceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FaceId {
      get { return faceId_; }
      set {
        faceId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MannequinData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MannequinData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AvatarData, other.AvatarData)) return false;
      if (IdleStance != other.IdleStance) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(IdleStanceLeftRightBlend, other.IdleStanceLeftRightBlend)) return false;
      if (PostureId != other.PostureId) return false;
      if (LeftHandPostureEnabled != other.LeftHandPostureEnabled) return false;
      if (RightHandPostureEnabled != other.RightHandPostureEnabled) return false;
      if (!object.Equals(PostureRotation, other.PostureRotation)) return false;
      if (MirrorPosture != other.MirrorPosture) return false;
      if (FaceId != other.FaceId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (avatarData_ != null) hash ^= AvatarData.GetHashCode();
      if (IdleStance != 0) hash ^= IdleStance.GetHashCode();
      if (IdleStanceLeftRightBlend != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(IdleStanceLeftRightBlend);
      if (PostureId != 0) hash ^= PostureId.GetHashCode();
      if (LeftHandPostureEnabled != false) hash ^= LeftHandPostureEnabled.GetHashCode();
      if (RightHandPostureEnabled != false) hash ^= RightHandPostureEnabled.GetHashCode();
      if (postureRotation_ != null) hash ^= PostureRotation.GetHashCode();
      if (MirrorPosture != false) hash ^= MirrorPosture.GetHashCode();
      if (FaceId != 0) hash ^= FaceId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (avatarData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AvatarData);
      }
      if (IdleStance != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(IdleStance);
      }
      if (IdleStanceLeftRightBlend != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(IdleStanceLeftRightBlend);
      }
      if (PostureId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PostureId);
      }
      if (LeftHandPostureEnabled != false) {
        output.WriteRawTag(40);
        output.WriteBool(LeftHandPostureEnabled);
      }
      if (RightHandPostureEnabled != false) {
        output.WriteRawTag(48);
        output.WriteBool(RightHandPostureEnabled);
      }
      if (postureRotation_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(PostureRotation);
      }
      if (MirrorPosture != false) {
        output.WriteRawTag(64);
        output.WriteBool(MirrorPosture);
      }
      if (FaceId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(FaceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (avatarData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AvatarData);
      }
      if (IdleStance != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(IdleStance);
      }
      if (IdleStanceLeftRightBlend != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(IdleStanceLeftRightBlend);
      }
      if (PostureId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PostureId);
      }
      if (LeftHandPostureEnabled != false) {
        output.WriteRawTag(40);
        output.WriteBool(LeftHandPostureEnabled);
      }
      if (RightHandPostureEnabled != false) {
        output.WriteRawTag(48);
        output.WriteBool(RightHandPostureEnabled);
      }
      if (postureRotation_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(PostureRotation);
      }
      if (MirrorPosture != false) {
        output.WriteRawTag(64);
        output.WriteBool(MirrorPosture);
      }
      if (FaceId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(FaceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (avatarData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AvatarData);
      }
      if (IdleStance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdleStance);
      }
      if (IdleStanceLeftRightBlend != 0F) {
        size += 1 + 4;
      }
      if (PostureId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PostureId);
      }
      if (LeftHandPostureEnabled != false) {
        size += 1 + 1;
      }
      if (RightHandPostureEnabled != false) {
        size += 1 + 1;
      }
      if (postureRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PostureRotation);
      }
      if (MirrorPosture != false) {
        size += 1 + 1;
      }
      if (FaceId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FaceId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MannequinData other) {
      if (other == null) {
        return;
      }
      if (other.avatarData_ != null) {
        if (avatarData_ == null) {
          AvatarData = new global::RecRoom.Protobuf.AvatarData();
        }
        AvatarData.MergeFrom(other.AvatarData);
      }
      if (other.IdleStance != 0) {
        IdleStance = other.IdleStance;
      }
      if (other.IdleStanceLeftRightBlend != 0F) {
        IdleStanceLeftRightBlend = other.IdleStanceLeftRightBlend;
      }
      if (other.PostureId != 0) {
        PostureId = other.PostureId;
      }
      if (other.LeftHandPostureEnabled != false) {
        LeftHandPostureEnabled = other.LeftHandPostureEnabled;
      }
      if (other.RightHandPostureEnabled != false) {
        RightHandPostureEnabled = other.RightHandPostureEnabled;
      }
      if (other.postureRotation_ != null) {
        if (postureRotation_ == null) {
          PostureRotation = new global::RecRoom.Protobuf.Core.Vector3Data();
        }
        PostureRotation.MergeFrom(other.PostureRotation);
      }
      if (other.MirrorPosture != false) {
        MirrorPosture = other.MirrorPosture;
      }
      if (other.FaceId != 0) {
        FaceId = other.FaceId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (avatarData_ == null) {
              AvatarData = new global::RecRoom.Protobuf.AvatarData();
            }
            input.ReadMessage(AvatarData);
            break;
          }
          case 16: {
            IdleStance = input.ReadInt32();
            break;
          }
          case 29: {
            IdleStanceLeftRightBlend = input.ReadFloat();
            break;
          }
          case 32: {
            PostureId = input.ReadInt32();
            break;
          }
          case 40: {
            LeftHandPostureEnabled = input.ReadBool();
            break;
          }
          case 48: {
            RightHandPostureEnabled = input.ReadBool();
            break;
          }
          case 58: {
            if (postureRotation_ == null) {
              PostureRotation = new global::RecRoom.Protobuf.Core.Vector3Data();
            }
            input.ReadMessage(PostureRotation);
            break;
          }
          case 64: {
            MirrorPosture = input.ReadBool();
            break;
          }
          case 72: {
            FaceId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (avatarData_ == null) {
              AvatarData = new global::RecRoom.Protobuf.AvatarData();
            }
            input.ReadMessage(AvatarData);
            break;
          }
          case 16: {
            IdleStance = input.ReadInt32();
            break;
          }
          case 29: {
            IdleStanceLeftRightBlend = input.ReadFloat();
            break;
          }
          case 32: {
            PostureId = input.ReadInt32();
            break;
          }
          case 40: {
            LeftHandPostureEnabled = input.ReadBool();
            break;
          }
          case 48: {
            RightHandPostureEnabled = input.ReadBool();
            break;
          }
          case 58: {
            if (postureRotation_ == null) {
              PostureRotation = new global::RecRoom.Protobuf.Core.Vector3Data();
            }
            input.ReadMessage(PostureRotation);
            break;
          }
          case 64: {
            MirrorPosture = input.ReadBool();
            break;
          }
          case 72: {
            FaceId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
