// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/persistence/roomie_customization_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/persistence/roomie_customization_data.proto</summary>
  public static partial class RoomieCustomizationDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/persistence/roomie_customization_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RoomieCustomizationDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRyZWNfcm9vbS9wZXJzaXN0ZW5jZS9yb29taWVfY3VzdG9taXphdGlvbl9k",
            "YXRhLnByb3RvEghyZWNfcm9vbRoUY29yZS9ndWlkX2RhdGEucHJvdG8aFWNv",
            "cmUvY29sb3JfZGF0YS5wcm90bxoXY29yZS92ZWN0b3IzX2RhdGEucHJvdG8i",
            "WQoXUm9vbWllQ3VzdG9taXphdGlvbkRhdGESPgoRb3V0Zml0X3NlbGVjdGlv",
            "bnMYASADKAsyIy5yZWNfcm9vbS5Sb29taWVPdXRmaXRTZWxlY3Rpb25EYXRh",
            "IoMEChlSb29taWVPdXRmaXRTZWxlY3Rpb25EYXRhEiYKDmF2YXRhcl9pdGVt",
            "X2lkGAEgASgLMg4uY29yZS5HdWlkRGF0YRIjCgVjb2xvchgCIAEoCzIPLmNv",
            "cmUuQ29sb3JEYXRhSACIAQESKAoIcm90YXRpb24YAyABKAsyES5jb3JlLlZl",
            "Y3RvcjNEYXRhSAGIAQESRQoJYm9keV9wYXJ0GAQgASgOMjIucmVjX3Jvb20u",
            "Um9vbWllT3V0Zml0U2VsZWN0aW9uRGF0YS5Sb29taWVCb2R5UGFydCKQAgoO",
            "Um9vbWllQm9keVBhcnQSCAoETm9uZRAAEggKBEhlYWQQARIJCgVXYWlzdBAC",
            "EgcKA0V5ZRADEgkKBU1vdXRoEAQSCAoEQmFjaxAFEggKBEZhY2UQBhINCglM",
            "ZWZ0V3Jpc3QQBxIOCgpSaWdodFdyaXN0EAgSCgoGVG9wcGVyEAkSBwoDRWFy",
            "EAoSCAoESGFpchALEggKBE1hc2sQDBIJCgVXaW5ncxANEggKBE5vc2UQDhIr",
            "Ch5EdW1teURvTm90U2VyaWFsaXplUHJpbWFyeVNraW4Q////////////ARIt",
            "CiBEdW1teURvTm90U2VyaWFsaXplU2Vjb25kYXJ5U2tpbhD+//////////8B",
            "QggKBl9jb2xvckILCglfcm90YXRpb25CE6oCEFJlY1Jvb20uUHJvdG9idWZi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::RecRoom.Protobuf.Core.GuidDataReflection.Descriptor, global::RecRoom.Protobuf.Core.ColorDataReflection.Descriptor, global::RecRoom.Protobuf.Core.Vector3DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.RoomieCustomizationData), global::RecRoom.Protobuf.RoomieCustomizationData.Parser, new[]{ "OutfitSelections" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.RoomieOutfitSelectionData), global::RecRoom.Protobuf.RoomieOutfitSelectionData.Parser, new[]{ "AvatarItemId", "Color", "Rotation", "BodyPart" }, new[]{ "Color", "Rotation" }, new[]{ typeof(global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RoomieCustomizationData : pb::IMessage<RoomieCustomizationData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoomieCustomizationData> _parser = new pb::MessageParser<RoomieCustomizationData>(() => new RoomieCustomizationData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoomieCustomizationData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.RoomieCustomizationDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomieCustomizationData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomieCustomizationData(RoomieCustomizationData other) : this() {
      outfitSelections_ = other.outfitSelections_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomieCustomizationData Clone() {
      return new RoomieCustomizationData(this);
    }

    /// <summary>Field number for the "outfit_selections" field.</summary>
    public const int OutfitSelectionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::RecRoom.Protobuf.RoomieOutfitSelectionData> _repeated_outfitSelections_codec
        = pb::FieldCodec.ForMessage(10, global::RecRoom.Protobuf.RoomieOutfitSelectionData.Parser);
    private readonly pbc::RepeatedField<global::RecRoom.Protobuf.RoomieOutfitSelectionData> outfitSelections_ = new pbc::RepeatedField<global::RecRoom.Protobuf.RoomieOutfitSelectionData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::RecRoom.Protobuf.RoomieOutfitSelectionData> OutfitSelections {
      get { return outfitSelections_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoomieCustomizationData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoomieCustomizationData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!outfitSelections_.Equals(other.outfitSelections_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= outfitSelections_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      outfitSelections_.WriteTo(output, _repeated_outfitSelections_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      outfitSelections_.WriteTo(ref output, _repeated_outfitSelections_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += outfitSelections_.CalculateSize(_repeated_outfitSelections_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoomieCustomizationData other) {
      if (other == null) {
        return;
      }
      outfitSelections_.Add(other.outfitSelections_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            outfitSelections_.AddEntriesFrom(input, _repeated_outfitSelections_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            outfitSelections_.AddEntriesFrom(ref input, _repeated_outfitSelections_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RoomieOutfitSelectionData : pb::IMessage<RoomieOutfitSelectionData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoomieOutfitSelectionData> _parser = new pb::MessageParser<RoomieOutfitSelectionData>(() => new RoomieOutfitSelectionData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoomieOutfitSelectionData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.RoomieCustomizationDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomieOutfitSelectionData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomieOutfitSelectionData(RoomieOutfitSelectionData other) : this() {
      avatarItemId_ = other.avatarItemId_ != null ? other.avatarItemId_.Clone() : null;
      color_ = other.color_ != null ? other.color_.Clone() : null;
      rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
      bodyPart_ = other.bodyPart_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomieOutfitSelectionData Clone() {
      return new RoomieOutfitSelectionData(this);
    }

    /// <summary>Field number for the "avatar_item_id" field.</summary>
    public const int AvatarItemIdFieldNumber = 1;
    private global::RecRoom.Protobuf.Core.GuidData avatarItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.Core.GuidData AvatarItemId {
      get { return avatarItemId_; }
      set {
        avatarItemId_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 2;
    private global::RecRoom.Protobuf.Core.ColorData color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.Core.ColorData Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 3;
    private global::RecRoom.Protobuf.Core.Vector3Data rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.Core.Vector3Data Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "body_part" field.</summary>
    public const int BodyPartFieldNumber = 4;
    private global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart bodyPart_ = global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart BodyPart {
      get { return bodyPart_; }
      set {
        bodyPart_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoomieOutfitSelectionData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoomieOutfitSelectionData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AvatarItemId, other.AvatarItemId)) return false;
      if (!object.Equals(Color, other.Color)) return false;
      if (!object.Equals(Rotation, other.Rotation)) return false;
      if (BodyPart != other.BodyPart) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (avatarItemId_ != null) hash ^= AvatarItemId.GetHashCode();
      if (color_ != null) hash ^= Color.GetHashCode();
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (BodyPart != global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart.None) hash ^= BodyPart.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (avatarItemId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AvatarItemId);
      }
      if (color_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Color);
      }
      if (rotation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Rotation);
      }
      if (BodyPart != global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) BodyPart);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (avatarItemId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AvatarItemId);
      }
      if (color_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Color);
      }
      if (rotation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Rotation);
      }
      if (BodyPart != global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) BodyPart);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (avatarItemId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AvatarItemId);
      }
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (BodyPart != global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BodyPart);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoomieOutfitSelectionData other) {
      if (other == null) {
        return;
      }
      if (other.avatarItemId_ != null) {
        if (avatarItemId_ == null) {
          AvatarItemId = new global::RecRoom.Protobuf.Core.GuidData();
        }
        AvatarItemId.MergeFrom(other.AvatarItemId);
      }
      if (other.color_ != null) {
        if (color_ == null) {
          Color = new global::RecRoom.Protobuf.Core.ColorData();
        }
        Color.MergeFrom(other.Color);
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          Rotation = new global::RecRoom.Protobuf.Core.Vector3Data();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      if (other.BodyPart != global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart.None) {
        BodyPart = other.BodyPart;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (avatarItemId_ == null) {
              AvatarItemId = new global::RecRoom.Protobuf.Core.GuidData();
            }
            input.ReadMessage(AvatarItemId);
            break;
          }
          case 18: {
            if (color_ == null) {
              Color = new global::RecRoom.Protobuf.Core.ColorData();
            }
            input.ReadMessage(Color);
            break;
          }
          case 26: {
            if (rotation_ == null) {
              Rotation = new global::RecRoom.Protobuf.Core.Vector3Data();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 32: {
            BodyPart = (global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (avatarItemId_ == null) {
              AvatarItemId = new global::RecRoom.Protobuf.Core.GuidData();
            }
            input.ReadMessage(AvatarItemId);
            break;
          }
          case 18: {
            if (color_ == null) {
              Color = new global::RecRoom.Protobuf.Core.ColorData();
            }
            input.ReadMessage(Color);
            break;
          }
          case 26: {
            if (rotation_ == null) {
              Rotation = new global::RecRoom.Protobuf.Core.Vector3Data();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 32: {
            BodyPart = (global::RecRoom.Protobuf.RoomieOutfitSelectionData.Types.RoomieBodyPart) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RoomieOutfitSelectionData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RoomieBodyPart {
        [pbr::OriginalName("None")] None = 0,
        [pbr::OriginalName("Head")] Head = 1,
        [pbr::OriginalName("Waist")] Waist = 2,
        [pbr::OriginalName("Eye")] Eye = 3,
        [pbr::OriginalName("Mouth")] Mouth = 4,
        [pbr::OriginalName("Back")] Back = 5,
        [pbr::OriginalName("Face")] Face = 6,
        [pbr::OriginalName("LeftWrist")] LeftWrist = 7,
        [pbr::OriginalName("RightWrist")] RightWrist = 8,
        [pbr::OriginalName("Topper")] Topper = 9,
        [pbr::OriginalName("Ear")] Ear = 10,
        [pbr::OriginalName("Hair")] Hair = 11,
        [pbr::OriginalName("Mask")] Mask = 12,
        [pbr::OriginalName("Wings")] Wings = 13,
        [pbr::OriginalName("Nose")] Nose = 14,
        [pbr::OriginalName("DummyDoNotSerializePrimarySkin")] DummyDoNotSerializePrimarySkin = -1,
        [pbr::OriginalName("DummyDoNotSerializeSecondarySkin")] DummyDoNotSerializeSecondarySkin = -2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
