// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/persistence/throw_handle_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/persistence/throw_handle_data.proto</summary>
  public static partial class ThrowHandleDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/persistence/throw_handle_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ThrowHandleDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixyZWNfcm9vbS9wZXJzaXN0ZW5jZS90aHJvd19oYW5kbGVfZGF0YS5wcm90",
            "bxIIcmVjX3Jvb20i0AMKD1Rocm93SGFuZGxlRGF0YRJIChFzY3JlZW5zX2lk",
            "bGVfcG9zZRgBIAEoDjItLnJlY19yb29tLlRocm93SGFuZGxlRGF0YS5UaHJv",
            "d0hhbmRsZUlkbGVQb3NlEkoKEnNjcmVlbnNfdGhyb3dfcG9zZRgCIAEoDjIu",
            "LnJlY19yb29tLlRocm93SGFuZGxlRGF0YS5UaHJvd0hhbmRsZVRocm93UG9z",
            "ZRIbChNzY3JlZW5zX3Rocm93X3NwZWVkGAMgASgCEhcKD21pbl90aHJvd19z",
            "cGVlZBgEIAEoAhIhChlERVBSRUNBVEVEX2NvbnRyb2xfcHJvbXB0GAUgASgJ",
            "IlkKE1Rocm93SGFuZGxlSWRsZVBvc2USEAoMREVGQVVMVF9JRExFEAASEgoO",
            "RE9ER0VCQUxMX0lETEUQARINCglEQVJUX0lETEUQAhINCglESVNDX0lETEUQ",
            "AyJzChRUaHJvd0hhbmRsZVRocm93UG9zZRIRCg1ERUZBVUxUX1RIUk9XEAAS",
            "EwoPRE9ER0VCQUxMX1RIUk9XEAESEwoPVU5ERVJIQU5EX1RIUk9XEAISDgoK",
            "REFSVF9USFJPVxADEg4KCkRJU0NfVEhST1cQBEITqgIQUmVjUm9vbS5Qcm90",
            "b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.ThrowHandleData), global::RecRoom.Protobuf.ThrowHandleData.Parser, new[]{ "ScreensIdlePose", "ScreensThrowPose", "ScreensThrowSpeed", "MinThrowSpeed", "DEPRECATEDControlPrompt" }, null, new[]{ typeof(global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose), typeof(global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ThrowHandleData : pb::IMessage<ThrowHandleData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ThrowHandleData> _parser = new pb::MessageParser<ThrowHandleData>(() => new ThrowHandleData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ThrowHandleData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.ThrowHandleDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThrowHandleData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThrowHandleData(ThrowHandleData other) : this() {
      screensIdlePose_ = other.screensIdlePose_;
      screensThrowPose_ = other.screensThrowPose_;
      screensThrowSpeed_ = other.screensThrowSpeed_;
      minThrowSpeed_ = other.minThrowSpeed_;
      dEPRECATEDControlPrompt_ = other.dEPRECATEDControlPrompt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThrowHandleData Clone() {
      return new ThrowHandleData(this);
    }

    /// <summary>Field number for the "screens_idle_pose" field.</summary>
    public const int ScreensIdlePoseFieldNumber = 1;
    private global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose screensIdlePose_ = global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose.DefaultIdle;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose ScreensIdlePose {
      get { return screensIdlePose_; }
      set {
        screensIdlePose_ = value;
      }
    }

    /// <summary>Field number for the "screens_throw_pose" field.</summary>
    public const int ScreensThrowPoseFieldNumber = 2;
    private global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose screensThrowPose_ = global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose.DefaultThrow;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose ScreensThrowPose {
      get { return screensThrowPose_; }
      set {
        screensThrowPose_ = value;
      }
    }

    /// <summary>Field number for the "screens_throw_speed" field.</summary>
    public const int ScreensThrowSpeedFieldNumber = 3;
    private float screensThrowSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ScreensThrowSpeed {
      get { return screensThrowSpeed_; }
      set {
        screensThrowSpeed_ = value;
      }
    }

    /// <summary>Field number for the "min_throw_speed" field.</summary>
    public const int MinThrowSpeedFieldNumber = 4;
    private float minThrowSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MinThrowSpeed {
      get { return minThrowSpeed_; }
      set {
        minThrowSpeed_ = value;
      }
    }

    /// <summary>Field number for the "DEPRECATED_control_prompt" field.</summary>
    public const int DEPRECATEDControlPromptFieldNumber = 5;
    private string dEPRECATEDControlPrompt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DEPRECATEDControlPrompt {
      get { return dEPRECATEDControlPrompt_; }
      set {
        dEPRECATEDControlPrompt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ThrowHandleData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ThrowHandleData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ScreensIdlePose != other.ScreensIdlePose) return false;
      if (ScreensThrowPose != other.ScreensThrowPose) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScreensThrowSpeed, other.ScreensThrowSpeed)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MinThrowSpeed, other.MinThrowSpeed)) return false;
      if (DEPRECATEDControlPrompt != other.DEPRECATEDControlPrompt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ScreensIdlePose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose.DefaultIdle) hash ^= ScreensIdlePose.GetHashCode();
      if (ScreensThrowPose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose.DefaultThrow) hash ^= ScreensThrowPose.GetHashCode();
      if (ScreensThrowSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScreensThrowSpeed);
      if (MinThrowSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MinThrowSpeed);
      if (DEPRECATEDControlPrompt.Length != 0) hash ^= DEPRECATEDControlPrompt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ScreensIdlePose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose.DefaultIdle) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ScreensIdlePose);
      }
      if (ScreensThrowPose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose.DefaultThrow) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ScreensThrowPose);
      }
      if (ScreensThrowSpeed != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(ScreensThrowSpeed);
      }
      if (MinThrowSpeed != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MinThrowSpeed);
      }
      if (DEPRECATEDControlPrompt.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DEPRECATEDControlPrompt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ScreensIdlePose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose.DefaultIdle) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ScreensIdlePose);
      }
      if (ScreensThrowPose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose.DefaultThrow) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ScreensThrowPose);
      }
      if (ScreensThrowSpeed != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(ScreensThrowSpeed);
      }
      if (MinThrowSpeed != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MinThrowSpeed);
      }
      if (DEPRECATEDControlPrompt.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DEPRECATEDControlPrompt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ScreensIdlePose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose.DefaultIdle) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ScreensIdlePose);
      }
      if (ScreensThrowPose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose.DefaultThrow) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ScreensThrowPose);
      }
      if (ScreensThrowSpeed != 0F) {
        size += 1 + 4;
      }
      if (MinThrowSpeed != 0F) {
        size += 1 + 4;
      }
      if (DEPRECATEDControlPrompt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DEPRECATEDControlPrompt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ThrowHandleData other) {
      if (other == null) {
        return;
      }
      if (other.ScreensIdlePose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose.DefaultIdle) {
        ScreensIdlePose = other.ScreensIdlePose;
      }
      if (other.ScreensThrowPose != global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose.DefaultThrow) {
        ScreensThrowPose = other.ScreensThrowPose;
      }
      if (other.ScreensThrowSpeed != 0F) {
        ScreensThrowSpeed = other.ScreensThrowSpeed;
      }
      if (other.MinThrowSpeed != 0F) {
        MinThrowSpeed = other.MinThrowSpeed;
      }
      if (other.DEPRECATEDControlPrompt.Length != 0) {
        DEPRECATEDControlPrompt = other.DEPRECATEDControlPrompt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ScreensIdlePose = (global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose) input.ReadEnum();
            break;
          }
          case 16: {
            ScreensThrowPose = (global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose) input.ReadEnum();
            break;
          }
          case 29: {
            ScreensThrowSpeed = input.ReadFloat();
            break;
          }
          case 37: {
            MinThrowSpeed = input.ReadFloat();
            break;
          }
          case 42: {
            DEPRECATEDControlPrompt = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ScreensIdlePose = (global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleIdlePose) input.ReadEnum();
            break;
          }
          case 16: {
            ScreensThrowPose = (global::RecRoom.Protobuf.ThrowHandleData.Types.ThrowHandleThrowPose) input.ReadEnum();
            break;
          }
          case 29: {
            ScreensThrowSpeed = input.ReadFloat();
            break;
          }
          case 37: {
            MinThrowSpeed = input.ReadFloat();
            break;
          }
          case 42: {
            DEPRECATEDControlPrompt = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ThrowHandleData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ThrowHandleIdlePose {
        [pbr::OriginalName("DEFAULT_IDLE")] DefaultIdle = 0,
        [pbr::OriginalName("DODGEBALL_IDLE")] DodgeballIdle = 1,
        [pbr::OriginalName("DART_IDLE")] DartIdle = 2,
        [pbr::OriginalName("DISC_IDLE")] DiscIdle = 3,
      }

      public enum ThrowHandleThrowPose {
        [pbr::OriginalName("DEFAULT_THROW")] DefaultThrow = 0,
        [pbr::OriginalName("DODGEBALL_THROW")] DodgeballThrow = 1,
        [pbr::OriginalName("UNDERHAND_THROW")] UnderhandThrow = 2,
        [pbr::OriginalName("DART_THROW")] DartThrow = 3,
        [pbr::OriginalName("DISC_THROW")] DiscThrow = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
