// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/persistence/tool_cleanup_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/persistence/tool_cleanup_data.proto</summary>
  public static partial class ToolCleanupDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/persistence/tool_cleanup_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ToolCleanupDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixyZWNfcm9vbS9wZXJzaXN0ZW5jZS90b29sX2NsZWFudXBfZGF0YS5wcm90",
            "bxIIcmVjX3Jvb20aF2NvcmUvdmVjdG9yM19kYXRhLnByb3RvIv8BCg9Ub29s",
            "Q2xlYW51cERhdGESQQoJb3ZlcnJpZGVzGAEgASgLMi4ucmVjX3Jvb20uVG9v",
            "bENsZWFudXBEYXRhLkNsZWFudXBPdmVycmlkZXNEYXRhEhIKCmlzX2FsbG93",
            "ZWQYAiABKAgalAEKFENsZWFudXBPdmVycmlkZXNEYXRhEiMKCHBvc2l0aW9u",
            "GAEgASgLMhEuY29yZS5WZWN0b3IzRGF0YRIjCghyb3RhdGlvbhgCIAEoCzIR",
            "LmNvcmUuVmVjdG9yM0RhdGESDQoFZGVsYXkYAyABKAISIwobZGlzYWJsZURl",
            "ZmF1bHRWaXN1YWxFZmZlY3RzGAQgASgIQhOqAhBSZWNSb29tLlByb3RvYnVm",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::RecRoom.Protobuf.Core.Vector3DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.ToolCleanupData), global::RecRoom.Protobuf.ToolCleanupData.Parser, new[]{ "Overrides", "IsAllowed" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.ToolCleanupData.Types.CleanupOverridesData), global::RecRoom.Protobuf.ToolCleanupData.Types.CleanupOverridesData.Parser, new[]{ "Position", "Rotation", "Delay", "DisableDefaultVisualEffects" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ToolCleanupData : pb::IMessage<ToolCleanupData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ToolCleanupData> _parser = new pb::MessageParser<ToolCleanupData>(() => new ToolCleanupData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ToolCleanupData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.ToolCleanupDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ToolCleanupData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ToolCleanupData(ToolCleanupData other) : this() {
      overrides_ = other.overrides_ != null ? other.overrides_.Clone() : null;
      isAllowed_ = other.isAllowed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ToolCleanupData Clone() {
      return new ToolCleanupData(this);
    }

    /// <summary>Field number for the "overrides" field.</summary>
    public const int OverridesFieldNumber = 1;
    private global::RecRoom.Protobuf.ToolCleanupData.Types.CleanupOverridesData overrides_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RecRoom.Protobuf.ToolCleanupData.Types.CleanupOverridesData Overrides {
      get { return overrides_; }
      set {
        overrides_ = value;
      }
    }

    /// <summary>Field number for the "is_allowed" field.</summary>
    public const int IsAllowedFieldNumber = 2;
    private bool isAllowed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAllowed {
      get { return isAllowed_; }
      set {
        isAllowed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ToolCleanupData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ToolCleanupData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Overrides, other.Overrides)) return false;
      if (IsAllowed != other.IsAllowed) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (overrides_ != null) hash ^= Overrides.GetHashCode();
      if (IsAllowed != false) hash ^= IsAllowed.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (overrides_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Overrides);
      }
      if (IsAllowed != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsAllowed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (overrides_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Overrides);
      }
      if (IsAllowed != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsAllowed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (overrides_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Overrides);
      }
      if (IsAllowed != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ToolCleanupData other) {
      if (other == null) {
        return;
      }
      if (other.overrides_ != null) {
        if (overrides_ == null) {
          Overrides = new global::RecRoom.Protobuf.ToolCleanupData.Types.CleanupOverridesData();
        }
        Overrides.MergeFrom(other.Overrides);
      }
      if (other.IsAllowed != false) {
        IsAllowed = other.IsAllowed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (overrides_ == null) {
              Overrides = new global::RecRoom.Protobuf.ToolCleanupData.Types.CleanupOverridesData();
            }
            input.ReadMessage(Overrides);
            break;
          }
          case 16: {
            IsAllowed = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (overrides_ == null) {
              Overrides = new global::RecRoom.Protobuf.ToolCleanupData.Types.CleanupOverridesData();
            }
            input.ReadMessage(Overrides);
            break;
          }
          case 16: {
            IsAllowed = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ToolCleanupData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class CleanupOverridesData : pb::IMessage<CleanupOverridesData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CleanupOverridesData> _parser = new pb::MessageParser<CleanupOverridesData>(() => new CleanupOverridesData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CleanupOverridesData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::RecRoom.Protobuf.ToolCleanupData.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CleanupOverridesData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CleanupOverridesData(CleanupOverridesData other) : this() {
          position_ = other.position_ != null ? other.position_.Clone() : null;
          rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
          delay_ = other.delay_;
          disableDefaultVisualEffects_ = other.disableDefaultVisualEffects_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CleanupOverridesData Clone() {
          return new CleanupOverridesData(this);
        }

        /// <summary>Field number for the "position" field.</summary>
        public const int PositionFieldNumber = 1;
        private global::RecRoom.Protobuf.Core.Vector3Data position_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::RecRoom.Protobuf.Core.Vector3Data Position {
          get { return position_; }
          set {
            position_ = value;
          }
        }

        /// <summary>Field number for the "rotation" field.</summary>
        public const int RotationFieldNumber = 2;
        private global::RecRoom.Protobuf.Core.Vector3Data rotation_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::RecRoom.Protobuf.Core.Vector3Data Rotation {
          get { return rotation_; }
          set {
            rotation_ = value;
          }
        }

        /// <summary>Field number for the "delay" field.</summary>
        public const int DelayFieldNumber = 3;
        private float delay_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Delay {
          get { return delay_; }
          set {
            delay_ = value;
          }
        }

        /// <summary>Field number for the "disableDefaultVisualEffects" field.</summary>
        public const int DisableDefaultVisualEffectsFieldNumber = 4;
        private bool disableDefaultVisualEffects_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool DisableDefaultVisualEffects {
          get { return disableDefaultVisualEffects_; }
          set {
            disableDefaultVisualEffects_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CleanupOverridesData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CleanupOverridesData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Position, other.Position)) return false;
          if (!object.Equals(Rotation, other.Rotation)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Delay, other.Delay)) return false;
          if (DisableDefaultVisualEffects != other.DisableDefaultVisualEffects) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (position_ != null) hash ^= Position.GetHashCode();
          if (rotation_ != null) hash ^= Rotation.GetHashCode();
          if (Delay != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Delay);
          if (DisableDefaultVisualEffects != false) hash ^= DisableDefaultVisualEffects.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (position_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Position);
          }
          if (rotation_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Rotation);
          }
          if (Delay != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(Delay);
          }
          if (DisableDefaultVisualEffects != false) {
            output.WriteRawTag(32);
            output.WriteBool(DisableDefaultVisualEffects);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (position_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Position);
          }
          if (rotation_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Rotation);
          }
          if (Delay != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(Delay);
          }
          if (DisableDefaultVisualEffects != false) {
            output.WriteRawTag(32);
            output.WriteBool(DisableDefaultVisualEffects);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (position_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
          }
          if (rotation_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
          }
          if (Delay != 0F) {
            size += 1 + 4;
          }
          if (DisableDefaultVisualEffects != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CleanupOverridesData other) {
          if (other == null) {
            return;
          }
          if (other.position_ != null) {
            if (position_ == null) {
              Position = new global::RecRoom.Protobuf.Core.Vector3Data();
            }
            Position.MergeFrom(other.Position);
          }
          if (other.rotation_ != null) {
            if (rotation_ == null) {
              Rotation = new global::RecRoom.Protobuf.Core.Vector3Data();
            }
            Rotation.MergeFrom(other.Rotation);
          }
          if (other.Delay != 0F) {
            Delay = other.Delay;
          }
          if (other.DisableDefaultVisualEffects != false) {
            DisableDefaultVisualEffects = other.DisableDefaultVisualEffects;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (position_ == null) {
                  Position = new global::RecRoom.Protobuf.Core.Vector3Data();
                }
                input.ReadMessage(Position);
                break;
              }
              case 18: {
                if (rotation_ == null) {
                  Rotation = new global::RecRoom.Protobuf.Core.Vector3Data();
                }
                input.ReadMessage(Rotation);
                break;
              }
              case 29: {
                Delay = input.ReadFloat();
                break;
              }
              case 32: {
                DisableDefaultVisualEffects = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (position_ == null) {
                  Position = new global::RecRoom.Protobuf.Core.Vector3Data();
                }
                input.ReadMessage(Position);
                break;
              }
              case 18: {
                if (rotation_ == null) {
                  Rotation = new global::RecRoom.Protobuf.Core.Vector3Data();
                }
                input.ReadMessage(Rotation);
                break;
              }
              case 29: {
                Delay = input.ReadFloat();
                break;
              }
              case 32: {
                DisableDefaultVisualEffects = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
