// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rec_room/persistence/trigger_handle_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RecRoom.Protobuf {

  /// <summary>Holder for reflection information generated from rec_room/persistence/trigger_handle_data.proto</summary>
  public static partial class TriggerHandleDataReflection {

    #region Descriptor
    /// <summary>File descriptor for rec_room/persistence/trigger_handle_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TriggerHandleDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5yZWNfcm9vbS9wZXJzaXN0ZW5jZS90cmlnZ2VyX2hhbmRsZV9kYXRhLnBy",
            "b3RvEghyZWNfcm9vbSJOChFUcmlnZ2VySGFuZGxlRGF0YRIXCg9zaG91bGRf",
            "cGxheV9zZngYASABKAgSIAoYREVQUkVDQVRFRF9jb250cm9sX2xhYmVsGAIg",
            "ASgJQhOqAhBSZWNSb29tLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RecRoom.Protobuf.TriggerHandleData), global::RecRoom.Protobuf.TriggerHandleData.Parser, new[]{ "ShouldPlaySfx", "DEPRECATEDControlLabel" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TriggerHandleData : pb::IMessage<TriggerHandleData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TriggerHandleData> _parser = new pb::MessageParser<TriggerHandleData>(() => new TriggerHandleData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TriggerHandleData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RecRoom.Protobuf.TriggerHandleDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerHandleData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerHandleData(TriggerHandleData other) : this() {
      shouldPlaySfx_ = other.shouldPlaySfx_;
      dEPRECATEDControlLabel_ = other.dEPRECATEDControlLabel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriggerHandleData Clone() {
      return new TriggerHandleData(this);
    }

    /// <summary>Field number for the "should_play_sfx" field.</summary>
    public const int ShouldPlaySfxFieldNumber = 1;
    private bool shouldPlaySfx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ShouldPlaySfx {
      get { return shouldPlaySfx_; }
      set {
        shouldPlaySfx_ = value;
      }
    }

    /// <summary>Field number for the "DEPRECATED_control_label" field.</summary>
    public const int DEPRECATEDControlLabelFieldNumber = 2;
    private string dEPRECATEDControlLabel_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DEPRECATEDControlLabel {
      get { return dEPRECATEDControlLabel_; }
      set {
        dEPRECATEDControlLabel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TriggerHandleData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TriggerHandleData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ShouldPlaySfx != other.ShouldPlaySfx) return false;
      if (DEPRECATEDControlLabel != other.DEPRECATEDControlLabel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ShouldPlaySfx != false) hash ^= ShouldPlaySfx.GetHashCode();
      if (DEPRECATEDControlLabel.Length != 0) hash ^= DEPRECATEDControlLabel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ShouldPlaySfx != false) {
        output.WriteRawTag(8);
        output.WriteBool(ShouldPlaySfx);
      }
      if (DEPRECATEDControlLabel.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DEPRECATEDControlLabel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ShouldPlaySfx != false) {
        output.WriteRawTag(8);
        output.WriteBool(ShouldPlaySfx);
      }
      if (DEPRECATEDControlLabel.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DEPRECATEDControlLabel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ShouldPlaySfx != false) {
        size += 1 + 1;
      }
      if (DEPRECATEDControlLabel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DEPRECATEDControlLabel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TriggerHandleData other) {
      if (other == null) {
        return;
      }
      if (other.ShouldPlaySfx != false) {
        ShouldPlaySfx = other.ShouldPlaySfx;
      }
      if (other.DEPRECATEDControlLabel.Length != 0) {
        DEPRECATEDControlLabel = other.DEPRECATEDControlLabel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ShouldPlaySfx = input.ReadBool();
            break;
          }
          case 18: {
            DEPRECATEDControlLabel = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ShouldPlaySfx = input.ReadBool();
            break;
          }
          case 18: {
            DEPRECATEDControlLabel = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
