// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: circuits/static/ev/ev_graph_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Circuits.Static.EV.Protobuf {

  /// <summary>Holder for reflection information generated from circuits/static/ev/ev_graph_data.proto</summary>
  public static partial class EvGraphDataReflection {

    #region Descriptor
    /// <summary>File descriptor for circuits/static/ev/ev_graph_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EvGraphDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZjaXJjdWl0cy9zdGF0aWMvZXYvZXZfZ3JhcGhfZGF0YS5wcm90bxIIY2ly",
            "Y3VpdHMaJmNpcmN1aXRzL3N0YXRpYy9ldi9ldl9pbnB1dF9kYXRhLnByb3Rv",
            "GiVjaXJjdWl0cy9zdGF0aWMvZXYvZXZfbm9kZV9kYXRhLnByb3RvGidjaXJj",
            "dWl0cy9zdGF0aWMvZXYvZXZfb3V0cHV0X2RhdGEucHJvdG8aKmNpcmN1aXRz",
            "L3N0YXRpYy9ldi9pbnB1dF9ncm91cHNfZGF0YS5wcm90bxorY2lyY3VpdHMv",
            "c3RhdGljL2V2L291dHB1dF9ncm91cHNfZGF0YS5wcm90bxouY2lyY3VpdHMv",
            "c2hhcmVkL3V0aWxpdGllcy9zb2FfaWRfMzJfZGF0YS5wcm90byLxAgoLRVZH",
            "cmFwaERhdGESDgoGZGVmX2lkGAEgASgFEg8KB3ZpcnRfaWQYAiABKAUSKAoJ",
            "ZXZfaW5wdXRzGAMgAygLMhUuY2lyY3VpdHMuRVZJbnB1dERhdGESKgoKZXZf",
            "b3V0cHV0cxgEIAMoCzIWLmNpcmN1aXRzLkVWT3V0cHV0RGF0YRImCghldl9u",
            "b2RlcxgFIAMoCzIULmNpcmN1aXRzLkVWTm9kZURhdGESLgoPaW5wdXRfZ3Jv",
            "dXBfaWRzGAYgASgLMhUuY2lyY3VpdHMuU09BSWQzMkRhdGESLwoMaW5wdXRf",
            "Z3JvdXBzGAcgAygLMhkuY2lyY3VpdHMuSW5wdXRHcm91cHNEYXRhEi8KEG91",
            "dHB1dF9ncm91cF9pZHMYCCABKAsyFS5jaXJjdWl0cy5TT0FJZDMyRGF0YRIx",
            "Cg1vdXRwdXRfZ3JvdXBzGAkgAygLMhouY2lyY3VpdHMuT3V0cHV0R3JvdXBz",
            "RGF0YUIeqgIbQ2lyY3VpdHMuU3RhdGljLkVWLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Circuits.Static.EV.Protobuf.EvInputDataReflection.Descriptor, global::Circuits.Static.EV.Protobuf.EvNodeDataReflection.Descriptor, global::Circuits.Static.EV.Protobuf.EvOutputDataReflection.Descriptor, global::Circuits.Static.EV.Protobuf.InputGroupsDataReflection.Descriptor, global::Circuits.Static.EV.Protobuf.OutputGroupsDataReflection.Descriptor, global::Circuits.Shared.Utilities.Protobuf.SoaId32DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Circuits.Static.EV.Protobuf.EVGraphData), global::Circuits.Static.EV.Protobuf.EVGraphData.Parser, new[]{ "DefId", "VirtId", "EvInputs", "EvOutputs", "EvNodes", "InputGroupIds", "InputGroups", "OutputGroupIds", "OutputGroups" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EVGraphData : pb::IMessage<EVGraphData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EVGraphData> _parser = new pb::MessageParser<EVGraphData>(() => new EVGraphData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EVGraphData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Circuits.Static.EV.Protobuf.EvGraphDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EVGraphData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EVGraphData(EVGraphData other) : this() {
      defId_ = other.defId_;
      virtId_ = other.virtId_;
      evInputs_ = other.evInputs_.Clone();
      evOutputs_ = other.evOutputs_.Clone();
      evNodes_ = other.evNodes_.Clone();
      inputGroupIds_ = other.inputGroupIds_ != null ? other.inputGroupIds_.Clone() : null;
      inputGroups_ = other.inputGroups_.Clone();
      outputGroupIds_ = other.outputGroupIds_ != null ? other.outputGroupIds_.Clone() : null;
      outputGroups_ = other.outputGroups_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EVGraphData Clone() {
      return new EVGraphData(this);
    }

    /// <summary>Field number for the "def_id" field.</summary>
    public const int DefIdFieldNumber = 1;
    private int defId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DefId {
      get { return defId_; }
      set {
        defId_ = value;
      }
    }

    /// <summary>Field number for the "virt_id" field.</summary>
    public const int VirtIdFieldNumber = 2;
    private int virtId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int VirtId {
      get { return virtId_; }
      set {
        virtId_ = value;
      }
    }

    /// <summary>Field number for the "ev_inputs" field.</summary>
    public const int EvInputsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Circuits.Static.EV.Protobuf.EVInputData> _repeated_evInputs_codec
        = pb::FieldCodec.ForMessage(26, global::Circuits.Static.EV.Protobuf.EVInputData.Parser);
    private readonly pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVInputData> evInputs_ = new pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVInputData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVInputData> EvInputs {
      get { return evInputs_; }
    }

    /// <summary>Field number for the "ev_outputs" field.</summary>
    public const int EvOutputsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Circuits.Static.EV.Protobuf.EVOutputData> _repeated_evOutputs_codec
        = pb::FieldCodec.ForMessage(34, global::Circuits.Static.EV.Protobuf.EVOutputData.Parser);
    private readonly pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVOutputData> evOutputs_ = new pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVOutputData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVOutputData> EvOutputs {
      get { return evOutputs_; }
    }

    /// <summary>Field number for the "ev_nodes" field.</summary>
    public const int EvNodesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Circuits.Static.EV.Protobuf.EVNodeData> _repeated_evNodes_codec
        = pb::FieldCodec.ForMessage(42, global::Circuits.Static.EV.Protobuf.EVNodeData.Parser);
    private readonly pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVNodeData> evNodes_ = new pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVNodeData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.EVNodeData> EvNodes {
      get { return evNodes_; }
    }

    /// <summary>Field number for the "input_group_ids" field.</summary>
    public const int InputGroupIdsFieldNumber = 6;
    private global::Circuits.Shared.Utilities.Protobuf.SOAId32Data inputGroupIds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Circuits.Shared.Utilities.Protobuf.SOAId32Data InputGroupIds {
      get { return inputGroupIds_; }
      set {
        inputGroupIds_ = value;
      }
    }

    /// <summary>Field number for the "input_groups" field.</summary>
    public const int InputGroupsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Circuits.Static.EV.Protobuf.InputGroupsData> _repeated_inputGroups_codec
        = pb::FieldCodec.ForMessage(58, global::Circuits.Static.EV.Protobuf.InputGroupsData.Parser);
    private readonly pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.InputGroupsData> inputGroups_ = new pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.InputGroupsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.InputGroupsData> InputGroups {
      get { return inputGroups_; }
    }

    /// <summary>Field number for the "output_group_ids" field.</summary>
    public const int OutputGroupIdsFieldNumber = 8;
    private global::Circuits.Shared.Utilities.Protobuf.SOAId32Data outputGroupIds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Circuits.Shared.Utilities.Protobuf.SOAId32Data OutputGroupIds {
      get { return outputGroupIds_; }
      set {
        outputGroupIds_ = value;
      }
    }

    /// <summary>Field number for the "output_groups" field.</summary>
    public const int OutputGroupsFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Circuits.Static.EV.Protobuf.OutputGroupsData> _repeated_outputGroups_codec
        = pb::FieldCodec.ForMessage(74, global::Circuits.Static.EV.Protobuf.OutputGroupsData.Parser);
    private readonly pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.OutputGroupsData> outputGroups_ = new pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.OutputGroupsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Circuits.Static.EV.Protobuf.OutputGroupsData> OutputGroups {
      get { return outputGroups_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EVGraphData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EVGraphData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DefId != other.DefId) return false;
      if (VirtId != other.VirtId) return false;
      if(!evInputs_.Equals(other.evInputs_)) return false;
      if(!evOutputs_.Equals(other.evOutputs_)) return false;
      if(!evNodes_.Equals(other.evNodes_)) return false;
      if (!object.Equals(InputGroupIds, other.InputGroupIds)) return false;
      if(!inputGroups_.Equals(other.inputGroups_)) return false;
      if (!object.Equals(OutputGroupIds, other.OutputGroupIds)) return false;
      if(!outputGroups_.Equals(other.outputGroups_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DefId != 0) hash ^= DefId.GetHashCode();
      if (VirtId != 0) hash ^= VirtId.GetHashCode();
      hash ^= evInputs_.GetHashCode();
      hash ^= evOutputs_.GetHashCode();
      hash ^= evNodes_.GetHashCode();
      if (inputGroupIds_ != null) hash ^= InputGroupIds.GetHashCode();
      hash ^= inputGroups_.GetHashCode();
      if (outputGroupIds_ != null) hash ^= OutputGroupIds.GetHashCode();
      hash ^= outputGroups_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DefId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DefId);
      }
      if (VirtId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(VirtId);
      }
      evInputs_.WriteTo(output, _repeated_evInputs_codec);
      evOutputs_.WriteTo(output, _repeated_evOutputs_codec);
      evNodes_.WriteTo(output, _repeated_evNodes_codec);
      if (inputGroupIds_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(InputGroupIds);
      }
      inputGroups_.WriteTo(output, _repeated_inputGroups_codec);
      if (outputGroupIds_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(OutputGroupIds);
      }
      outputGroups_.WriteTo(output, _repeated_outputGroups_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DefId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DefId);
      }
      if (VirtId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(VirtId);
      }
      evInputs_.WriteTo(ref output, _repeated_evInputs_codec);
      evOutputs_.WriteTo(ref output, _repeated_evOutputs_codec);
      evNodes_.WriteTo(ref output, _repeated_evNodes_codec);
      if (inputGroupIds_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(InputGroupIds);
      }
      inputGroups_.WriteTo(ref output, _repeated_inputGroups_codec);
      if (outputGroupIds_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(OutputGroupIds);
      }
      outputGroups_.WriteTo(ref output, _repeated_outputGroups_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DefId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DefId);
      }
      if (VirtId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VirtId);
      }
      size += evInputs_.CalculateSize(_repeated_evInputs_codec);
      size += evOutputs_.CalculateSize(_repeated_evOutputs_codec);
      size += evNodes_.CalculateSize(_repeated_evNodes_codec);
      if (inputGroupIds_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InputGroupIds);
      }
      size += inputGroups_.CalculateSize(_repeated_inputGroups_codec);
      if (outputGroupIds_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputGroupIds);
      }
      size += outputGroups_.CalculateSize(_repeated_outputGroups_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EVGraphData other) {
      if (other == null) {
        return;
      }
      if (other.DefId != 0) {
        DefId = other.DefId;
      }
      if (other.VirtId != 0) {
        VirtId = other.VirtId;
      }
      evInputs_.Add(other.evInputs_);
      evOutputs_.Add(other.evOutputs_);
      evNodes_.Add(other.evNodes_);
      if (other.inputGroupIds_ != null) {
        if (inputGroupIds_ == null) {
          InputGroupIds = new global::Circuits.Shared.Utilities.Protobuf.SOAId32Data();
        }
        InputGroupIds.MergeFrom(other.InputGroupIds);
      }
      inputGroups_.Add(other.inputGroups_);
      if (other.outputGroupIds_ != null) {
        if (outputGroupIds_ == null) {
          OutputGroupIds = new global::Circuits.Shared.Utilities.Protobuf.SOAId32Data();
        }
        OutputGroupIds.MergeFrom(other.OutputGroupIds);
      }
      outputGroups_.Add(other.outputGroups_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DefId = input.ReadInt32();
            break;
          }
          case 16: {
            VirtId = input.ReadInt32();
            break;
          }
          case 26: {
            evInputs_.AddEntriesFrom(input, _repeated_evInputs_codec);
            break;
          }
          case 34: {
            evOutputs_.AddEntriesFrom(input, _repeated_evOutputs_codec);
            break;
          }
          case 42: {
            evNodes_.AddEntriesFrom(input, _repeated_evNodes_codec);
            break;
          }
          case 50: {
            if (inputGroupIds_ == null) {
              InputGroupIds = new global::Circuits.Shared.Utilities.Protobuf.SOAId32Data();
            }
            input.ReadMessage(InputGroupIds);
            break;
          }
          case 58: {
            inputGroups_.AddEntriesFrom(input, _repeated_inputGroups_codec);
            break;
          }
          case 66: {
            if (outputGroupIds_ == null) {
              OutputGroupIds = new global::Circuits.Shared.Utilities.Protobuf.SOAId32Data();
            }
            input.ReadMessage(OutputGroupIds);
            break;
          }
          case 74: {
            outputGroups_.AddEntriesFrom(input, _repeated_outputGroups_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DefId = input.ReadInt32();
            break;
          }
          case 16: {
            VirtId = input.ReadInt32();
            break;
          }
          case 26: {
            evInputs_.AddEntriesFrom(ref input, _repeated_evInputs_codec);
            break;
          }
          case 34: {
            evOutputs_.AddEntriesFrom(ref input, _repeated_evOutputs_codec);
            break;
          }
          case 42: {
            evNodes_.AddEntriesFrom(ref input, _repeated_evNodes_codec);
            break;
          }
          case 50: {
            if (inputGroupIds_ == null) {
              InputGroupIds = new global::Circuits.Shared.Utilities.Protobuf.SOAId32Data();
            }
            input.ReadMessage(InputGroupIds);
            break;
          }
          case 58: {
            inputGroups_.AddEntriesFrom(ref input, _repeated_inputGroups_codec);
            break;
          }
          case 66: {
            if (outputGroupIds_ == null) {
              OutputGroupIds = new global::Circuits.Shared.Utilities.Protobuf.SOAId32Data();
            }
            input.ReadMessage(OutputGroupIds);
            break;
          }
          case 74: {
            outputGroups_.AddEntriesFrom(ref input, _repeated_outputGroups_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
